In [98]:
import pandas as pd

In [99]:
df_sport = pd.read_csv("Olympic_Athlete_Event_Details.csv")

In [100]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
316829,2022 Winter Olympics,62,NED,Bobsleigh,"Monobob, Women",19019671,Karlien Sleper,148662,16,NaN,False
316830,2022 Winter Olympics,62,SVK,Bobsleigh,"Monobob, Women",19019671,Viktória Čerňanská,138683,17,NaN,False
316831,2022 Winter Olympics,62,KOR,Bobsleigh,"Monobob, Women",19019671,Kim Yu-Ran,137542,18,NaN,False
316832,2022 Winter Olympics,62,JAM,Bobsleigh,"Monobob, Women",19019671,Jazmine Fenlator-Victorian,128682,19,NaN,False
316833,2022 Winter Olympics,62,UKR,Bobsleigh,"Monobob, Women",19019671,Lidiya Hunko,149047,20,NaN,False

In [101]:
df_sport.shape

(316834, 11)

In [102]:
df_sport = df_sport[~df_sport["edition"].str.contains(r"Winter Olympics", case=False, na=False)]

In [103]:
df_sport.shape

(254981, 11)

In [104]:
len(df_sport['sport'].unique())

92

In [105]:
df_sport['sport'].unique()

array(['Athletics', 'Boxing', 'Diving', 'Rugby', 'Shooting', 'Swimming',
       'Rowing', 'Tennis', 'Artistic Gymnastics', 'Cycling Track',
       'Fencing', 'Wrestling', 'Art Competitions', 'Cycling Road',
       'Artistic Swimming', 'Judo', 'Sailing', 'Weightlifting',
       'Taekwondo', 'Archery', 'Golf', 'Canoe Sprint',
       'Cycling Mountain Bike', 'Modern Pentathlon', 'Handball',
       'Triathlon', 'Basketball', 'Roller Hockey', 'Beach Volleyball',
       'Hockey', 'Football', 'Badminton', 'Rhythmic Gymnastics',
       'Equestrian Jumping', 'Wushu', 'Canoe Slalom', 'Karate',
       'Table Tennis', 'Equestrian Eventing', 'Equestrian Dressage',
       'Volleyball', 'Trampolining', 'Marathon Swimming',
       'Cycling BMX Freestyle', 'Surfing', 'Baseball', 'Waterskiing',
       'Cycling BMX Racing', 'Rugby Sevens', 'Skateboarding',
       'Water Polo', 'Bowling', 'Softball', 'Sport Climbing',
       'Basque pelota', 'Gliding', 'Figure Skating', 'Polo',
       'Automobile Racing', 'Equestrian Driving', 'Equestrian Vaulting',
       'Ice Hockey', 'Tug-Of-War', 'Savate', 'Canoe Marathon',
       '3x3 Basketball', 'Glíma', 'Australian Rules Football',
       'Pesäpallo', 'Lacrosse', 'Firefighting', 'Bicycle Polo',
       'Alpinism', 'Kendo', 'Korfball', 'Kaatsen', 'Cricket',
       'Jeu De Paume', 'Motorboating', 'Racquets', 'Lifesaving',
       'Ballooning', 'Boules', 'Croquet', 'Fishing', 'Longue Paume',
       'Military Exercise', 'Motorcycle Sports', 'Canne De Combat',
       'Aeronautics', 'American Football', 'Roque'], dtype=object)

In [106]:
len(df_sport['event'].unique())

856

In [107]:
df_sport['event'].unique()

array(['100 metres, Men', '400 metres, Men', '800 metres, Men',
       '1,500 metres, Men', '5 miles, Men', 'Marathon, Men',
       '110 metres Hurdles, Men', '400 metres Hurdles, Men',
       '3,200 metres Steeplechase, Men', '3,500 metres Race Walk, Men',
       '10 miles Race Walk, Men', 'Standing High Jump, Men',
       'Long Jump, Men', 'Standing Long Jump, Men', 'Triple Jump, Men',
       'Lightweight, Men', 'Middleweight, Men', 'Springboard, Men',
       'Rugby, Men', 'Small-Bore Rifle, Prone, 50 and 100 yards, Men',
       'Small-Bore Rifle, Disappearing Target, 25 yards, Men',
       'Small-Bore Rifle, Moving Target, 25 yards, Men',
       '100 metres Freestyle, Men', '400 metres Freestyle, Men',
       '1,500 metres Freestyle, Men',
       '4 × 200 metres Freestyle Relay, Men',
       '100 metres Backstroke, Men', '200 metres Breaststroke, Men',
       '200 metres, Men', '5,000 metres, Men', '10,000 metres, Men',
       '10 kilometres Race Walk, Men', 'Cross-Country, Individual, Men',
       'Single Sculls, Men', 'Eights, Men',
       '400 metres Breaststroke, Men', '100 metres Freestyle, Women',
       'Singles, Covered Courts, Men', 'Individual All-Around, Men',
       'Standing Triple Jump, Men', 'Discus Throw, Men', 'Sprint, Men',
       'Sprint, Professionals, Men', 'Tandem Sprint, Professionals, Men',
       'Points Race, Professionals, Men',
       '3,000 metres, Handicap, Professionals, Men', 'Singles, Women',
       'Singles, Handicap, Women', 'Doubles, Mixed',
       'Doubles, Handicap, Mixed', 'Shot Put, Men',
       'Discus Throw, Greek Style, Men', 'Javelin Throw, Freestyle, Men',
       'Épée, Individual, Men', 'Épée, Team, Men',
       'Sabre, Individual, Men', 'Sabre, Team, Men',
       'Foil, Individual, Open', 'Singles, Men', 'Doubles, Men',
       'Lightweight, Greco-Roman, Men', 'Middleweight, Greco-Roman, Men',
       'Light-Heavyweight, Greco-Roman, Men', 'Sculpturing, Open',
       '4 × 100 metres Relay, Men', '4 × 400 metres Relay, Men',
       'Pole Vault, Men', 'Hammer Throw, Men', 'Pentathlon, Men',
       'Decathlon, Men', 'Road Race, Individual, Men',
       'Road Race, Team, Men', 'Foil, Individual, Men',
       'Doubles, Covered Courts, Men', 'Doubles, Covered Courts, Mixed',
       'Featherweight, Greco-Roman, Men',
       'Middleweight B, Greco-Roman, Men', 'Solo, Women', 'Duet, Women',
       '100 metres, Women', '200 metres, Women', 'Marathon, Women',
       'Light-Welterweight, Men', 'Light-Heavyweight, Men',
       'Windsurfer, Men', 'Half-Lightweight, Men',
       '50 metres Freestyle, Men', '50 metres Freestyle, Women',
       '100 metres Butterfly, Men', 'Middle-Heavyweight, Men',
       'Half-Middleweight, Men', '800 metres Freestyle, Women',
       'Super-Heavyweight, Men', 'One Person Dinghy, Women',
       'Multihull, Mixed', '200 metres Freestyle, Men',
       'Flyweight, Women', 'Air Pistol, 10 metres, Men',
       '100 metres Breaststroke, Men', 'Air Rifle, 10 metres, Women',
       'Long Jump, Women', 'Air Rifle, 10 metres, Men',
       'Small-Bore Rifle, Three Positions, 50 metres, Women',
       '100 metres Breaststroke, Women', 'Individual, Men',
       'Floor Exercise, Men', 'Parallel Bars, Men', 'Horizontal Bar, Men',
       'Individual, Women', 'Team, Mixed', 'Team, Men', 'Team, Women',
       'Extra-Lightweight, Men', 'Welterweight, Men',
       'Heavyweight II, Men', 'Heavyweight, Freestyle, Men',
       'Light-Middleweight, Men', 'Shot Put, Women',
       'Two Person Keelboat, Open', 'Light-Heavyweight, Freestyle, Men',
       'Hammer Throw, Women', 'Heavyweight, Men',
       'Half-Middleweight, Women', 'Half-Heavyweight, Men',
       'Two Person Dinghy, Men', '1,000 metres Time Trial, Men',
       'Individual Pursuit, 4,000 metres, Men', '400 metres, Women',
       '800 metres, Women', '1,500 metres, Women',
       '4 × 400 metres Relay, Women', 'Points Race, Men',
       'Bantamweight, Men', 'Windsurfer, Open', 'One Person Dinghy, Men',
       '4 × 100 metres Relay, Women',
       'Canadian Doubles, 1,000 metres, Men',
       'Kayak Singles, 500 metres, Women', 'Cross-Country, Men',
       'One Person Dinghy, Open', 'High Jump, Men', 'High Jump, Women',
       'Rapid-Fire Pistol, 25 metres, Men',
       'Small-Bore Rifle, Prone, 50 metres, Men', 'Trap, Open',
       '3,000 metres Steeplechase, Men', 'Flyweight, Men',
       'Featherweight, Men', 'Javelin Throw, Men',
       '100 kilometres Team Time Trial, Men',
       'Three Person Keelboat, Open', '5,000 metres, Women',
       '10,000 metres, Women', '3,000 metres Steeplechase, Women',
       'Welterweight, Freestyle, Men', '400 metres Hurdles, Women',
       'Handball, Men', 'Skeet, Women', 'Light-Flyweight, Men',
       '100 metres Hurdles, Women', 'Heptathlon, Women',
       'Small-Bore Rifle, Prone, 50 metres, Open',
       'Free Pistol, 50 metres, Open', 'Road Race, Individual, Women',
       'Triple Jump, Women', 'Kayak Singles, 200 metres, Men',
       'Kayak Singles, 1,000 metres, Men', '200 metres Butterfly, Men',
       '200 metres Individual Medley, Men',
       '400 metres Individual Medley, Men', 'Skeet, Open',
       'Horse Vault, Men', 'Rings, Men', 'Pommelled Horse, Men',
       'Skeet, Men', '200 metres Backstroke, Men',
       '400 metres Freestyle, Women', 'Olympic Distance, Men',
       '100 metres Backstroke, Women',
       'Sporting Pistol, 25 metres, Women', 'Javelin Throw, Women',
       'Air Pistol, 10 metres, Women', 'Lightweight, Freestyle, Men',
       'Lightweight, Women', 'Heavyweight, Greco-Roman, Men',
       'Half-Lightweight, Women', 'Free Pistol, 50 metres, Men',
       '100 metres Butterfly, Women', 'Featherweight, Women',
       '4 × 100 metres Medley Relay, Men', '3,000 metres, Women',
       'Basketball, Men', 'Roller Hockey, Men', 'Handball, Women',
       'Trap, Men', '200 metres Breaststroke, Women',
       'Middleweight, Women', 'Beach Volleyball, Men',
       'Canadian Singles, 500 metres, Men',
       'Canadian Singles, 1,000 metres, Men', 'Basketball, Women',
       'Canadian Singles, 200 metres, Men',
       'Lightweight Double Sculls, Men', 'Hockey, Men', 'Football, Men',
       'Flyweight, Freestyle, Men', 'Featherweight, Freestyle, Men',
       'Middleweight, Freestyle, Men', 'Bantamweight, Greco-Roman, Men',
       'Bantamweight, Freestyle, Men', 'Light-Flyweight, Freestyle, Men',
       'Platform, Men', 'Light-Flyweight, Greco-Roman, Men',
       '20 kilometres Race Walk, Women', 'Welterweight, Greco-Roman, Men',
       'Super-Heavyweight, Freestyle, Men', 'Sabre, Individual, Women',
       'Individual, Open', 'Group, Women',
       'Super-Heavyweight, Greco-Roman, Men',
       'Flyweight, Freestyle, Women', 'Lightweight, Freestyle, Women',
       'Middleweight, Freestyle, Women', 'Sanshou (≤56 kilograms), Men',
       'Sanshou (≤85 kilograms), Men', 'Individual Time Trial, Women',
       'Single Sculls, Women', 'Welterweight, Women',
       'Kayak Singles, Slalom, Men', 'Kayak Singles, 200 metres, Women',
       'Sprint, Women', 'Keirin, Women', 'Double Sculls, Men',
       'Featherweight, Freestyle, Women', 'Individual All-Around, Women',
       'Floor Exercise, Women', 'Horse Vault, Women',
       'Uneven Bars, Women', 'Balance Beam, Women',
       'Extra-Lightweight, Women', 'Heavyweight, Women',
       'Kumite, ≤67 kg, Men', 'Kumite, ≤75 kg, Men',
       'Kumite, >61 kg, Women', 'Light-Heavyweight, Freestyle, Women',
       'Springboard, Women',
       'Small-Bore Rifle, Three Positions, 50 metres, Men',
       'Heavyweight I, Men', 'Flyweight, Greco-Roman, Men',
       'Kayak Singles, 500 metres, Men', 'Sanshou (≤70 kilograms), Men',
       'Light-Heavyweight, Women', 'Super-Heavyweight, Women',
       'Half-Heavyweight, Women', 'Two Person Dinghy, Open',
       '10 kilometres Race Walk, Women', '200 metres Butterfly, Women',
       '200 metres Backstroke, Women', 'Windsurfer, Women',
       '200 metres Individual Medley, Women',
       'Kayak Singles, Slalom, Women', 'Canadian Singles, Slalom, Women',
       'Two Person Heavyweight Dinghy, Open', '5.5 metres, Open',
       'Multihull, Open', '4 × 100 metres Freestyle Relay, Men',
       'Two Person Keelboat, Men', 'Three Person Keelboat, Women',
       'Olympic Distance, Women', 'Skiff, Men',
       'Architecture, Further Entries, Open',
       '20 kilometres Race Walk, Men', '50 kilometres Race Walk, Men',
       '200 metres Freestyle, Women',
       'Military Rifle, Kneeling Or Standing, 300 metres, Men',
       'Volleyball, Men', 'Foil, Individual, Women',
       'Épée, Individual, Women', '400 metres Individual Medley, Women',
       'Doubles, Women', 'Volleyball, Women',
       'Individual Time Trial, Men', '10 kilometres Open Water, Women',
       'Discus Throw, Women', 'Pentathlon, Women',
       'Heavyweight, Freestyle, Women', 'Football, Women',
       'Team All-Around, Men', 'Team All-Around, Women',
       'Canadian Doubles, 500 metres, Men', 'Points Race, Women',
       'Coxless Pairs, Men', 'Quadruple Sculls, Men', 'Eights, Women',
       '4 × 100 metres Freestyle Relay, Women',
       '4 × 200 metres Freestyle Relay, Women',
       'Kayak Doubles, 500 metres, Women',
       'Kayak Fours, 500 metres, Women', 'Kayak Doubles, 500 metres, Men',
       'Kayak Fours, 1,000 metres, Men', '500 metres Time Trial, Women',
       'Coxless Pairs, Women', 'Quadruple Sculls, Women',
       'Running Target, 10 metres, Men', 'Coxless Fours, Men',
       'Pole Vault, Women', 'Kayak Doubles, 200 metres, Men',
       'Team Pursuit, Women', 'Omnium, Women', 'Double Sculls, Women',
       'Kayak Doubles, 1,000 metres, Men', 'Kayak Fours, 500 metres, Men',
       'Canadian Singles, 200 metres, Women',
       'Canadian Doubles, 500 metres, Women', 'Omnium, Men',
       'Lightweight Double Sculls, Women',
       'Air Rifle, 10 metres, Team, Mixed',
       '4 × 100 metres Medley Relay, Women',
       '4 × 100 metres Medley Relay, Mixed',
       'Small-Bore Rifle, Three Positions, 50 metres, Open',
       'Rapid-Fire Pistol, 25 metres, Open', 'Platform, Women',
       'Cross-Country, Women', 'Beach Volleyball, Women', 'Park, Men',
       'Shortboard, Men', 'Shortboard, Women', 'Unknown Event, Open',
       '80 metres Hurdles, Women', 'Individual Pursuit, Women',
       '800 metres Freestyle, Men',
       'Free Rifle, Three Positions, 300 metres, Open',
       'Running Target, 50 metres, Open', 'Open Class, Men',
       'Synchronized Platform, Women', 'Trap, Women', 'Baseball, Men',
       'Double Trap, Men', '4 × 400 metres Relay, Mixed', 'Music, Open',
       'Team Pursuit, 4,000 metres, Men', 'Foil, Team, Men',
       'Tandem Sprint, 2,000 metres, Men', 'Slalom, Men',
       'Running Target, 50 metres, Men', 'Team, Open', 'Madison, Men',
       'BMX, Men', 'Synchronized Platform, Men', 'BMX, Women',
       'Keirin, Men', 'Team Sprint, Women', 'Rugby Sevens, Women',
       'Street, Men', 'Finweight, Men', 'Canadian Singles, Slalom, Men',
       'Coxed Fours, Men', 'Water Polo, Men', 'Skiff, Open',
       'One Person Heavyweight Dinghy, Men', 'Two Person Dinghy, Women',
       'Kumite, >75 kg, Men', '10 kilometres Open Water, Men',
       'Free Rifle, Three Positions, 300 metres, Men', 'Finweight, Women',
       'Bantamweight, Women', 'Softball, Women', 'Double Trap, Women',
       'Daoshu & Gunshu, Men', 'Nanquan & Nangun, Men',
       'Taijiquan & Taijijuan, Men', 'Nanquan & Nandao, Women',
       'Jianshu & Qiangshu, Women', 'Taijiquan & Taijijuan, Women',
       'Kata, Men', 'Kumite, ≤55 kg, Women',
       'Dueling Pistol, 30 metres, Men',
       'Military Rifle, Three Positions, 300 metres, Men',
       'Military Rifle, Any Position, 600 metres, Men',
       '50 kilometres, Men', 'Coxed Pairs, Men',
       'Lightweight Coxless Fours, Men', 'Skiff, Women', 'Park, Women',
       '1,500 metres Freestyle, Women', 'Rugby Sevens, Men',
       'Canadian Doubles, Slalom, Men', 'Team Sprint, Men',
       'Combined, Men', 'Épée, Masters and Amateurs, Individual, Men',
       '6 metres, Open', 'Foil, Team, Women', 'Mano, Doubles, Men',
       'Mano, Singles, Men', 'Pala Corta, Doubles, Men',
       'Frontenis, Doubles, Men', 'Frontenis, Doubles, Women',
       'Épée, Team, Women', 'Synchronized Springboard, Men',
       'Air Pistol, 10 metres, Team, Mixed',
       '3,000 metres Race Walk, Men', 'Coxed Fours, Women',
       'Coxed Quadruple Sculls, Women', 'Painting, Graphic Arts, Open',
       'Painting, Paintings, Open', 'Gliding, Open',
       'Team Portable Apparatus, Women', 'Coxless Fours, Women',
       'Painting, Open', 'Sanshou (≤60 kilograms), Women',
       'Kumite, ≤61 kg, Women', 'Trap, Team, Mixed',
       'Foil, Masters, Individual, Men', 'Épée, Masters, Individual, Men',
       'Free Rifle, Prone, 600 metres, Men',
       'Free Rifle, 400, 600 and 800 metres, Team, Men', 'Polo, Men',
       '8 metres, Open', 'Paleta Cuero, Doubles, Men',
       'Paleta Goma, Doubles, Men', 'Tricks, Men', 'Hockey, Women',
       'Au Chapelet, 33 metres, Men', 'Au Chapelet, 50 metres, Men',
       'Au Cordon Doré, 33 metres, Men', 'Au Cordon Doré, 50 metres, Men',
       'Sur La Perche À La Herse, Men',
       'Sur La Perche À La Pyramide, Men', 'Championnat Du Monde, Men',
       '100 metres, Handicap, Men', '400 metres Hurdles, Handicap, Men',
       '400 metres, Professionals, Men',
       '1,500 metres, Professionals, Men',
       '6-hour race, Professionals, Men',
       '110 metres Hurdles, Professionals, Men',
       '2,500 metres Steeplechase, Professionals, Men',
       'Paris-Toulouse-Paris, Cars, Men',
       'Team Sprint, Professionals, Men',
       '50 kilometres, Professionals, Men',
       '100 kilometres, Professionals, Men',
       '100 miles, Professionals, Men', 'Hacks and Hunter Combined, Open',
       'Four-In-Hand Competition, Open', 'Long Jump, Open',
       'High Jump, Open', 'Sabre, Masters, Individual, Men',
       'Coxless Pairs, Boys', 'Coxless Fours, Boys', 'Eights, Boys',
       'Free Pistol, 50 metres, Team, Men',
       'Free Rifle, Three Positions, 300 metres, Team, Men',
       'Free Rifle, Kneeling, 300 metres, Men',
       'Free Rifle, Prone, 300 metres, Men',
       'Free Rifle, Standing, 300 metres, Men',
       '1,000 metres Freestyle, Men', '4,000 metres Freestyle, Men',
       '20 kilometres, Men', '100 kilometres, Men',
       'Free Pistol, 50 yards, Men', 'Free Pistol, 50 yards, Team, Men',
       'Coxed Fours, Outriggers, Men',
       'Target Archery, 28 metres, Individual, Men',
       'Target Archery, 33 metres, Individual, Men',
       'Target Archery, 50 metres, Individual, Men',
       'Target Archery, 28 metres, Team, Men',
       'Target Archery, 33 metres, Team, Men',
       'Target Archery, 50 metres, Team, Men',
       'Pole Archery, Small Birds, Individual, Men',
       'Pole Archery, Large Birds, Individual, Men',
       'Pole Archery, Small Birds, Team, Men',
       'Pole Archery, Large Birds, Team, Men', 'Literature, Open',
       'Team All-Around, Swedish System, Men', '3,000 metres, Team, Men',
       'Cross-Country, Team, Men', 'Plain High, Men', 'Pairs, Mixed',
       'Ice Hockey, Men', 'Military Pistol, Team, Men',
       'Military Rifle, Prone, 300 metres, Team, Men',
       'Military Rifle, Prone, 600 metres, Team, Men',
       'Military Rifle, Standing, 300 metres, Men',
       'Military Rifle, Standing, 300 metres, Team, Men',
       'Military Rifle, Prone, 300 and 600 metres, Team, Men',
       'Small-Bore Rifle, Standing, 50 metres, Men',
       'Smal-Bore Rifle, Standing, 50 metres, Team, Men',
       'Trap, Team, Men', 'Unknown Event, Men', 'Tug-Of-War, Men',
       'Plain High, Women', 'Savate, Men', 'Literature, Epic Works, Open',
       'Literature, Lyric Works, Open',
       'Music, Compositions For Orchestra, Open',
       'Music, Instrumental And Chamber, Open',
       'Painting, Drawings And Water Colors, Open',
       'Sculpturing, Medals And Reliefs, Open',
       'Sculpturing, Statues, Open',
       'Architecture, Designs For Town Planning, Open',
       'Painting, Unknown Event, Open',
       'Sculpturing, Unknown Event, Open', 'Sculpturing, Medals, Open',
       'Sculpturing, Reliefs, Open', 'Kayak Singles, 10,000 metres, Men',
       'Kayak Doubles, 10,000 metres, Men',
       'Folding Kayak Singles, 10,000 metres, Men',
       'Folding Kayak Doubles, 10,000 metres, Men',
       'Canadian Doubles, 10,000 metres, Men',
       'Kayak Relay, 4 × 500 metres, Men', '1,500 metres Wheelchair, Men',
       '3x3 Basketball, Men', 'Madison, Women', 'Street, Women',
       'Relay, Mixed', 'Changquan, Men', 'Jianshu & Qiangshu, Men',
       'Changquan, Women', 'Daoshu & Gunshu, Women', 'Kata, Women',
       'Military Pistol, 30 metres, Men', 'Architecture, Open',
       'Sanshou (≤52 kilograms), Women',
       'Synchronized Springboard, Women', 'Water Polo, Women',
       'Rope Climbing, Men', 'Side Horse, Men',
       'Running Target, Single Shot, Men',
       'Running Target, Single Shot, Team, Men',
       'Running Target, Double Shot, Men',
       'Running Target, Double Shot, Team, Men',
       'Literature, Dramatic Works, Open',
       'Music, Compositions For Solo Or Chorus, Open',
       'Painting, Applied Arts, Open',
       'Architecture, Architectural Designs, Open',
       'Music, Unknown Event, Open',
       'Sculpturing, Medals And Plaques, Open',
       'Canadian Singles, 10,000 metres, Men', 'Glíma, Men',
       'Free Pistol, 30 metres, Men', 'Military Pistol, 25 metres, Men',
       'Muzzle-Loading Pistol, 25 metres, Men',
       'Free Rifle, Any Position, 300 metres, Men',
       'Military Rifle, 200 metres, Men', '500 metres Freestyle, Men',
       '1,200 metres Freestyle, Men', 'Unlimited, One Hand, Men',
       'Unlimited, Two Hands, Men', '800 metres, Handicap, Men',
       '1,500 metres, Handicap, Men', 'Underwater Swimming, Men',
       'Military Rifle, 200/500/600/800/900/1,000 yards, Team, Men',
       'Team All-Around, Free System, Men', 'Coxed Fours, Inriggers, Men',
       'Military Rifle, 200, 400, 500 and 600 metres, Team, Men',
       'Small-Bore Rifle, Any Position, 50 metres, Men',
       'Small-Bore Rifle, Prone, 50 metres, Team, Men',
       'Small-Bore Rifle, Disappearing Target, 25 metres, Men',
       'Singles, Covered Courts, Women',
       'Middleweight A, Greco-Roman, Men',
       'Military Rifle, Prone, 300 metres, Men',
       'Military Rifle, Prone, 600 metres, Men',
       '800 metres Wheelchair, Women', '333⅓ metres Time Trial, Men',
       '12-Hours Race, Men', '2,500 metres Steeplechase, Men',
       '2,500 metres Steeplechase, Handicap, Men',
       '200 metres Obstacle Course, Men', 'Discus Throw, Both Hands, Men',
       'Combined, Women', 'Jumping, Men', '60 metres, Men',
       '200 metres Hurdles, Men', '110 metres Hurdles, Handicap, Men',
       'Parallel Bars, Teams, Men',
       '100 metres Freestyle For Sailors, Men',
       'Unlimited Class, Greco-Roman, Men',
       'Free Rifle, 1,000 yards, Men', 'Shot Put, Both Hands, Men',
       'Javelin Throw, Both Hands, Men',
       'Dueling Pistol, 30 metres, Team, Men',
       'Small-Bore Rifle, Disappearing Target, 25 metres, Team, Men',
       '100 metres, Professionals, Handicap, Men',
       '400 metres, Professionals, Handicap, Men',
       '100 yards, Handicap, Men', '120 yards Hurdles, Handicap, Men',
       '⅓ mile, Professionals, Men', '1 mile, Professionals, Men',
       'Australian Team Pursuit, Professionals, Men',
       '1 mile, Handicap, Professionals, Men',
       '2 miles, Handicap, Professionals, Men',
       '300 metres Freestyle, Women', 'Australian Rules Football, Men',
       'Running Target, Single and Double Shot, Men', 'Slalom, Women',
       'Tricks, Women', 'Jumping, Women', '10 metres, Open',
       '12 metres, Open', '56-pound Weight Throw, Men', 'Pesäpallo, Men',
       '3x3 Basketball, Women', 'Singles, Handicap, Men',
       'Doubles, Handicap, Men', 'Cesta Punta, Doubles, Men',

In [108]:
df_sport[df_sport['sport'] == 'Tug-Of-War']

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport
37082,1920 Summer Olympics,7,BEL,Tug-Of-War,"Tug-Of-War, Men",21134,Edouard Bourguignon,11273,3,Bronze,True
37083,1920 Summer Olympics,7,BEL,Tug-Of-War,"Tug-Of-War, Men",21134,Alphonse Ducatillon,11274,3,Bronze,True
37084,1920 Summer Olympics,7,BEL,Tug-Of-War,"Tug-Of-War, Men",21134,Rémy Maertens,11275,3,Bronze,True
37085,1920 Summer Olympics,7,BEL,Tug-Of-War,"Tug-Of-War, Men",21134,Christin Piek,11276,3,Bronze,True
37086,1920 Summer Olympics,7,BEL,Tug-Of-War,"Tug-Of-War, Men",21134,Henri Pintens,11277,3,Bronze,True
...,...,...,...,...,...,...,...,...,...,...,...
297664,1920 Summer Olympics,7,USA,Tug-Of-War,"Tug-Of-War, Men",21134,Lloyd Kelsey,18273,4,NaN,True
297665,1920 Summer Olympics,7,USA,Tug-Of-War,"Tug-Of-War, Men",21134,Joseph Kszyczewski,18275,4,NaN,True
297666,1920 Summer Olympics,7,USA,Tug-Of-War,"Tug-Of-War, Men",21134,William Penn,18279,4,NaN,True
297667,1920 Summer Olympics,7,USA,Tug-Of-War,"Tug-Of-War, Men",21134,Joseph Rond,18281,4,NaN,True
297668,1920 Summer Olympics,7,USA,Tug-Of-War,"Tug-Of-War, Men",21134,Joseph Winston,18287,4,NaN,True

In [109]:
df_sport.loc[:, "year"] = df_sport["edition"].str.extract(r"(\d{4})").astype(int)

C:\Users\santi\AppData\Local\Temp\ipykernel_9360\2319291170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sport.loc[:, "year"] = df_sport["edition"].str.extract(r"(\d{4})").astype(int)

In [110]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False,1908
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False,1908
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False,1908
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False,1908
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False,1908
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [111]:
df_socioec = pd.read_csv("clean_df_medals_indicators_summerOnly.csv")
df_socioec

,edition,edition_id,year,country,country_noc,gold,silver,bronze,total,paese_olimpiade,...,NY.GNP.PCAP.CD,SE.PRM.ENRR,SH.DYN.NMRT,SP.DYN.IMRT.IN,SP.DYN.LE00.IN,SP.POP.1564.TO.ZS,SP.POP.GROW,SP.POP.TOTL,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
0,1964 Summer Olympics,16.0,1964.0,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964.0,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964.0,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964.0,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964.0,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020.0,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020.0,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020.0,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020.0,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020.0,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [112]:
df_socioec["year"] = df_socioec[("year")].astype(int)
df_socioec

,edition,edition_id,year,country,country_noc,gold,silver,bronze,total,paese_olimpiade,...,NY.GNP.PCAP.CD,SE.PRM.ENRR,SH.DYN.NMRT,SP.DYN.IMRT.IN,SP.DYN.LE00.IN,SP.POP.1564.TO.ZS,SP.POP.GROW,SP.POP.TOTL,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
0,1964 Summer Olympics,16.0,1964,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [113]:
df_sport.shape

(254981, 12)

In [114]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False,1908
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False,1908
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False,1908
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False,1908
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False,1908
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [115]:
years_ok = df_socioec["year"].unique()
df_sport = df_sport.loc[df_sport["year"].isin(years_ok)]

In [116]:
df_sport.shape

(179141, 12)

In [117]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
363,1988 Summer Olympics,22,ARU,Artistic Swimming,"Solo, Women",43507,Roswitha Lopez,44994,18,NaN,False,1988
364,1988 Summer Olympics,22,ARU,Artistic Swimming,"Solo, Women",43507,Yvette Thuis,44995,AC r1/3,NaN,False,1988
365,1988 Summer Olympics,22,ARU,Artistic Swimming,"Duet, Women",43511,Yvette Thuis,44995,15,NaN,True,1988
366,1988 Summer Olympics,22,ARU,Artistic Swimming,"Duet, Women",43511,Roswitha Lopez,44994,15,NaN,True,1988
367,1988 Summer Olympics,22,ARU,Athletics,"100 metres, Women",63682,Evelyn Farrell,64471,8 h7 r1/4,NaN,False,1988
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [118]:
df_sport['year'].unique()

array([1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 1984, 1976,
       1972, 1980, 1968, 1964])

In [119]:
df_socioec['year'].unique()

array([1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004,
       2008, 2012, 2016, 2020])

In [120]:
df_socioec['country'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'The Bahamas', 'Republic of Korea', 'Trinidad and Tobago',
       'Tunisia', 'Argentina', 'Cuba', 'Pakistan', 'Philippines',
       'Islamic Republic of Iran', 'Brazil', 'Ghana', 'Ireland', 'Kenya',
       'Mexico', 'Nigeria', 'Uruguay', 'East Germany', 'West Germany',
       'Norway', 'Venezuela', 'Austria', 'Mongolia', 'Uganda', 'Cameroon',
       'Jamaica', 'Chinese Taipei', 'Greece',
       "Democratic People's Republic of Korea", 'Colombia', 'Lebanon',
       'Niger', 'Spain', 'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand',
       'Zimbabwe', 'United Republic of Tanzania', 'Guyana',
       "People's Republic of China", 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Republic of Moldova',
       'Uzbekistan', 'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique',
       'Kingdom of Saudi Arabia', 'Sri Lanka', 'Vietnam', 'Barbados',
       'Kuwait', 'Kyrgyzstan', 'North Macedonia', 'United Arab Emirates',
       'Paraguay', 'Eritrea', 'Panama', 'Serbia', 'Tajikistan', 'Samoa',
       'Singapore', 'Sudan', 'Afghanistan', 'Mauritius', 'Togo',
       'Bahrain', 'Grenada', 'Botswana', 'Cyprus', 'Gabon', 'Guatemala',
       'Montenegro', 'Fiji', 'Jordan', 'Kosovo', 'ROC', 'San Marino',
       'Turkmenistan', 'Burkina Faso', 'Aruba', 'Angola', 'Albania',
       'Andorra', 'American Samoa', 'Antigua and Barbuda', 'Benin',
       'Bangladesh', 'Bahamas', 'Bosnia and Herzegovina', 'Belize',
       'Brunei Darussalam', 'Bhutan', 'Central African Republic', 'China',
       'Congo', 'Comoros', 'Cabo Verde', 'Cayman Islands', 'Dominica',
       'Guinea', 'Gambia', 'Guinea-Bissau', 'Equatorial Guinea',
       'Greenland', 'Guam', 'Hong Kong', 'Honduras', 'Haiti', 'Iraq',
       'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'Somalia', 'South Sudan',
       'Sao Tome and Principe', 'Eswatini', 'Seychelles', 'Chad',
       'Timor-Leste', 'Tuvalu', 'Saint Vincent and the Grenadines',
       'Virgin Islands (U.S.)', 'Viet Nam', 'Vanuatu', 'Yemen',
       'United States of America', 'Hong Kong, China',
       'Bolivia, Plurinational State of',
       'Congo, Democratic Republic of the',
       'Micronesia, Federated States of', 'Iran, Islamic Republic of',
       'Moldova, Republic of', 'Netherlands, Kingdom of the',
       "Korea, Democratic People's Republic of", 'Palestine, State of',
       'Tanzania, United Republic of',
       'Venezuela, Bolivarian Republic of', 'Korea, Republic of'],
      dtype=object)

In [121]:
mapping_varianti = {
    "Iran, Islamic Republic of": "Iran",
    "Islamic Republic of Iran": "Iran",
    "Tanzania, United Republic of": "Tanzania",
    "United Republic of Tanzania": "Tanzania",
    "Moldova, Republic of": "Moldova",
    "Republic of Moldova": "Moldova",
    "Venezuela, Bolivarian Republic of": "Venezuela",
    "Viet Nam": "Vietnam",
    "Congo, Democratic Republic of the": "Democratic Republic of the Congo",
    "The Bahamas": "Bahamas",
    "Korea, Republic of": "South Korea",
    "Republic of Korea": "South Korea",
    "Korea, Democratic People's Republic of": "North Korea",
    "Democratic People's Republic of Korea": "North Korea",
    "People's Republic of China": "China",
    "Hong Kong, China": "Hong Kong",
    "United States of America": "United States",
    "Kingdom of Saudi Arabia": "Saudi Arabia",
    "Palestine, State of": "Palestine"
}

In [122]:
mapping_speciali = {
    #"Independent Olympic Athletes": "Independent"???,
    #"ROC": "Russia"--> Russia che non può gareggiare come russia ma come comitato olimpico,
    "Virgin Islands (U.S.)": "United States Virgin Islands",
    "United States Virgin Islands": "United States Virgin Islands"
}

In [123]:
country_mapping = {
    **mapping_varianti,
    **mapping_speciali
}

In [124]:
df_socioec["country"] = df_socioec["country"].replace(country_mapping)

In [125]:
df_socioec['country'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'Bahamas', 'South Korea', 'Trinidad and Tobago', 'Tunisia',
       'Argentina', 'Cuba', 'Pakistan', 'Philippines', 'Iran', 'Brazil',
       'Ghana', 'Ireland', 'Kenya', 'Mexico', 'Nigeria', 'Uruguay',
       'East Germany', 'West Germany', 'Norway', 'Venezuela', 'Austria',
       'Mongolia', 'Uganda', 'Cameroon', 'Jamaica', 'Chinese Taipei',
       'Greece', 'North Korea', 'Colombia', 'Lebanon', 'Niger', 'Spain',
       'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand', 'Zimbabwe',
       'Tanzania', 'Guyana', 'China', 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Moldova', 'Uzbekistan',
       'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique', 'Saudi Arabia',
       'Sri Lanka', 'Vietnam', 'Barbados', 'Kuwait', 'Kyrgyzstan',
       'North Macedonia', 'United Arab Emirates', 'Paraguay', 'Eritrea',
       'Panama', 'Serbia', 'Tajikistan', 'Samoa', 'Singapore', 'Sudan',
       'Afghanistan', 'Mauritius', 'Togo', 'Bahrain', 'Grenada',
       'Botswana', 'Cyprus', 'Gabon', 'Guatemala', 'Montenegro', 'Fiji',
       'Jordan', 'Kosovo', 'ROC', 'San Marino', 'Turkmenistan',
       'Burkina Faso', 'Aruba', 'Angola', 'Albania', 'Andorra',
       'American Samoa', 'Antigua and Barbuda', 'Benin', 'Bangladesh',
       'Bosnia and Herzegovina', 'Belize', 'Brunei Darussalam', 'Bhutan',
       'Central African Republic', 'Congo', 'Comoros', 'Cabo Verde',
       'Cayman Islands', 'Dominica', 'Guinea', 'Gambia', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greenland', 'Guam', 'Hong Kong', 'Honduras',
       'Haiti', 'Iraq', 'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Solomon Islands', 'Sierra Leone',
       'El Salvador', 'Somalia', 'South Sudan', 'Sao Tome and Principe',
       'Eswatini', 'Seychelles', 'Chad', 'Timor-Leste', 'Tuvalu',
       'Saint Vincent and the Grenadines', 'Vanuatu', 'Yemen',
       'Bolivia, Plurinational State of',
       'Democratic Republic of the Congo',
       'Micronesia, Federated States of', 'Netherlands, Kingdom of the',
       'Palestine'], dtype=object)

In [126]:
noc_atleti = df_sport["country_noc"].unique()

In [127]:
paesi_socio = df_socioec["country_noc"].unique()

In [128]:
set(noc_atleti) - set(paesi_socio)

{'ANG',
 'ANT',
 'ARU',
 'ASA',
 'BAN',
 'BHU',
 'BIZ',
 'BRU',
 'CAM',
 'CAY',
 'CGO',
 'CHA',
 'COK',
 'EOR',
 'ESA',
 'GAM',
 'GBS',
 'GEQ',
 'GUI',
 'HAI',
 'HON',
 'IVB',
 'LBA',
 'LES',
 'MAD',
 'MAW',
 'MON',
 'MTN',
 'MYA',
 'NCA',
 'NEP',
 'OMA',
 'PLE',
 'SEY',
 'SKN',
 'SOL',
 'URS',
 'VAN',
 'VIN',
 'YAR',
 'YMD'}

In [129]:
len(set(noc_atleti) - set(paesi_socio))

41

In [130]:
df_sport[(df_sport['country_noc'] == 'COK') & (df_sport['medal'].notna())]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year]
Index: []

In [131]:
df_sport[(df_sport['country_noc'] == 'IVB') & (df_sport['medal'].notna())]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year]
Index: []

In [132]:
df_sport[(df_sport['country_noc'] == 'YMD') & (df_sport['medal'].notna())]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year]
Index: []

In [133]:
len(set(noc_atleti) - set(paesi_socio))

41

In [134]:
mapping_noc = {
    'Angola': 'ANG',
    'Antigua and Barbuda': 'ANT',
    'Aruba': 'ARU',
    'American Samoa': 'ASA',
    'Bangladesh': 'BAN',
    'Bhutan': 'BHU',
    'Belize': 'BIZ',
    'Brunei Darussalam': 'BRU',
    'Cambodia': 'CAM',
    'Cayman Islands': 'CAY',
    'Congo': 'CGO',
    'Chad': 'CHA',
    #'COK', --> 'Cook Islands' non c'è nel dataset degli indicatori socio-economici. Dopo aver controllato se ci sono atleti che hanno vinto medaglia risulta un df vuoto, quindi non avendo mai vinto una medaglia potremmo eliminarlo dall'analisi.
    #'EOR', --> squadra olimpica dei rifugiati, si potrebbe togliere dall'analisi visto che non c'è un unico paese di corrispondenza e quindi non abbiamo indicatori socioeconomici?
    'El Salvador': 'ESA',
    'Gambia': 'GAM',
    'Guinea-Bissau': 'GBS',
    'Equatorial Guinea': 'GEQ',
    'Guinea': 'GUI',
    'Haiti': 'HAI',
    'Honduras': 'HON',
    #'IVB', --> British Virgin Islands. Non ci sono nel dataset socio-economico. non hanno mai vinto medaglia, potremmo eliminarle dall'analisi
    'Libya': 'LBA',
    'Lesotho': 'LES',
    'Madagascar': 'MAD',
    'Malawi': 'MAW',
    'Monaco': 'MON',
    'Mauritania': 'MTN',
    'Myanmar': 'MYA',
    'Nicaragua': 'NCA',
    'Nepal': 'NEP',
    'Oman': 'OMA',
    'Palestine': 'PLE',
    'Seychelles': 'SEY',
    'Saint Kitts and Nevis': 'SKN',
    'Solomon Islands': 'SOL',
    'Soviet Union': 'URS',
    'Vanuatu': 'VAN',
    'Saint Vincent and the Grenadines': 'VIN',
    #'YAR', --> North Yemen. Si può eliminare, non ha mai vinto medaglia
    # 'YMD' --> South Yemen. Si può eliminare, non ha mai vinto medaglia,
    'Democratic Republic of the Congo' :'COD',
    'Russian Olympic Committee': 'ROC'
}

In [135]:
mask = df_socioec["country"].isin(mapping_noc.keys())

df_socioec.loc[mask, "country_noc"] = df_socioec.loc[mask, "country"].map(mapping_noc)

In [136]:
df_sport = df_sport[~df_sport['country_noc'].isin(['COK', 'EOR', 'IVB', 'YAR', 'YMD'])]

In [137]:
team_rows = df_sport[df_sport['isTeamSport'] == True]
ind_rows  = df_sport[df_sport['isTeamSport'] == False]

team_dedup = team_rows.drop_duplicates(subset=['year', 'country_noc', 'event', 'medal'])
df_clean = pd.concat([ind_rows, team_dedup], ignore_index=True)

print(f"Righe originali: {len(df_sport):,}")
print(f"Righe dopo dedup team sport: {len(df_clean):,}")

Righe originali: 178,980
Righe dopo dedup team sport: 120,684

Dataset macro_sport

In [138]:
def aggrega_medaglie(group):
    return pd.Series({
        'num_athletes': group['athlete_id'].nunique(),
        'gold':   (group['medal'] == 'Gold').sum(),
        'silver': (group['medal'] == 'Silver').sum(),
        'bronze': (group['medal'] == 'Bronze').sum(),
    })

df_macro_sport = df_clean.groupby(['country_noc', 'year', 'sport']).apply(
    aggrega_medaglie
).reset_index()

df_macro_sport['total_medals'] = (
    df_macro_sport['gold'] + df_macro_sport['silver'] + df_macro_sport['bronze']
)
df_macro_sport

C:\Users\santi\AppData\Local\Temp\ipykernel_9360\460937068.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_macro_sport = df_clean.groupby(['country_noc', 'year', 'sport']).apply(

,country_noc,year,sport,num_athletes,gold,silver,bronze,total_medals
0,AFG,1964,Wrestling,8,0,0,0,0
1,AFG,1968,Wrestling,5,0,0,0,0
2,AFG,1972,Wrestling,8,0,0,0,0
3,AFG,1980,Boxing,3,0,0,0,0
4,AFG,1980,Wrestling,8,0,0,0,0
...,...,...,...,...,...,...,...,...
20952,ZIM,2016,Swimming,2,0,0,0,0
20953,ZIM,2020,Athletics,1,0,0,0,0
20954,ZIM,2020,Golf,1,0,0,0,0
20955,ZIM,2020,Rowing,1,0,0,0,0
20956,ZIM,2020,Swimming,2,0,0,0,0

In [139]:
df_countries = pd.read_csv("Olympic_Country_Profiles.csv")
df_countries = df_countries.rename(columns={'noc': 'country_noc'})

df_macro_sport = df_macro_sport.merge(df_countries, on='country_noc', how='left')
cols = list(df_macro_sport.columns)
cols.insert(cols.index('country_noc') + 1, cols.pop(cols.index('country')))
df_macro_sport = df_macro_sport[cols]
df_macro_sport.to_csv("Macro_sports.csv", index=False)
df_macro_sport

,country_noc,country,year,sport,num_athletes,gold,silver,bronze,total_medals
0,AFG,Afghanistan,1964,Wrestling,8,0,0,0,0
1,AFG,Afghanistan,1968,Wrestling,5,0,0,0,0
2,AFG,Afghanistan,1972,Wrestling,8,0,0,0,0
3,AFG,Afghanistan,1980,Boxing,3,0,0,0,0
4,AFG,Afghanistan,1980,Wrestling,8,0,0,0,0
...,...,...,...,...,...,...,...,...,...
20991,ZIM,Zimbabwe,2016,Swimming,2,0,0,0,0
20992,ZIM,Zimbabwe,2020,Athletics,1,0,0,0,0
20993,ZIM,Zimbabwe,2020,Golf,1,0,0,0,0
20994,ZIM,Zimbabwe,2020,Rowing,1,0,0,0,0
20995,ZIM,Zimbabwe,2020,Swimming,2,0,0,0,0

Dataset sugli sport nel tempo

In [140]:
import numpy as np

sport_year_rows = []

for (sport, year), grp in df_clean.groupby(['sport', 'year']):

    n_nations = grp['country_noc'].nunique()

    athletes_per_event = grp.groupby('event')['athlete_id'].nunique().mean()

    event_team_flag = grp.groupby('event')['isTeamSport'].first()
    pct_team_events = event_team_flag.mean()

    medals = grp[grp['medal'].notna()]
    if len(medals) > 0:
        gold_by_country = medals[medals['medal'] == 'Gold'].groupby('country_noc').size()
        total_gold = gold_by_country.sum()
        hhi = ((gold_by_country / total_gold) ** 2).sum() if total_gold > 0 else np.nan
        n_nations_with_gold = gold_by_country.shape[0]
    else:
        hhi = np.nan
        n_nations_with_gold = 0

    sport_year_rows.append({
        'sport': sport,
        'year': year,
        'n_nations': n_nations,
        'n_events': grp['event'].nunique(),
        'athletes_per_event': athletes_per_event,
        'pct_team_events': pct_team_events,
        'hhi_gold': hhi,
        'n_nations_with_gold': n_nations_with_gold,
    })

df_sport_year = pd.DataFrame(sport_year_rows)
df_sport_year.to_csv("Sport_features_by_year.csv", index=False)
df_sport_year

,sport,year,n_nations,n_events,athletes_per_event,pct_team_events,hhi_gold,n_nations_with_gold
0,3x3 Basketball,2020,13,2,8.000000,1.0,0.500000,2
1,Archery,1972,27,2,47.500000,0.0,1.000000,1
2,Archery,1976,24,2,32.000000,0.0,1.000000,1
3,Archery,1980,25,2,33.500000,0.0,0.500000,2
4,Archery,1984,35,2,54.500000,0.0,0.500000,2
...,...,...,...,...,...,...,...,...
512,Wrestling,2008,59,18,19.055556,0.0,0.197531,10
513,Wrestling,2012,71,18,19.055556,0.0,0.185596,7
514,Wrestling,2016,66,18,19.277778,0.0,0.141975,10
515,Wrestling,2020,60,18,16.000000,0.0,0.179012,8
516,Wushu,2008,42,15,8.066667,0.0,NaN,0

Dataset sport aggregati per anno

In [141]:
df_sport_profile = df_sport_year.groupby('sport').agg(
    n_nations_mean       = ('n_nations',            'mean'),
    n_nations_max        = ('n_nations',            'max'),
    athletes_per_event   = ('athletes_per_event',   'mean'),
    pct_team_events      = ('pct_team_events',       'mean'),
    hhi_gold_mean        = ('hhi_gold',             'mean'),
    n_nations_with_gold  = ('n_nations_with_gold',  'mean'),
    n_editions           = ('year',                 'nunique'),
).reset_index()

df_sport_profile.to_csv("Sport_profile_static.csv", index=False)
df_sport_profile

,sport,n_nations_mean,n_nations_max,athletes_per_event,pct_team_events,hhi_gold_mean,n_nations_with_gold,n_editions
0,3x3 Basketball,13.000000,13,8.000000,1.000000,0.500000,2.000000,1
1,Archery,41.307692,56,40.246154,0.353846,0.648462,1.923077,13
2,Artistic Gymnastics,36.200000,60,74.304762,0.142857,0.275273,6.266667,15
3,Artistic Swimming,20.800000,24,19.450000,0.850000,0.955556,1.100000,10
4,Athletics,147.333333,199,40.007725,0.091415,0.140041,17.533333,15
5,Badminton,35.000000,51,23.510000,0.580000,0.487500,2.300000,10
6,Baseball,7.111111,8,7.111111,1.000000,1.000000,0.666667,9
7,Basketball,16.200000,19,11.933333,1.000000,0.833333,1.333333,15
8,Basque pelota,7.500000,8,4.425000,1.000000,NaN,0.000000,2
9,Beach Volleyball,23.000000,24,19.285714,1.000000,0.571429,1.857143,7
10,Bowling,20.000000,20,12.000000,0.000000,NaN,0.000000,1
11,Boxing,75.266667,105,27.041896,0.000000,0.239113,6.933333,15
12,Canoe Slalom,26.000000,33,21.277778,0.222222,0.416667,3.111111,9
13,Canoe Sprint,37.333333,50,17.623088,0.559235,0.269726,5.733333,15
14,Cycling BMX Freestyle,11.000000,11,9.000000,0.000000,0.500000,2.000000,1
15,Cycling BMX Racing,21.750000,23,24.000000,0.000000,0.500000,2.000000,4
16,Cycling Mountain Bike,35.000000,41,38.928571,0.000000,0.500000,2.000000,7
17,Cycling Road,52.533333,70,74.788889,0.233333,0.421296,2.866667,15
18,Cycling Track,36.866667,53,21.180794,0.295635,0.359919,4.466667,15
19,Diving,28.266667,42,24.483333,0.200000,0.550000,2.533333,15
20,Equestrian Dressage,17.000000,29,25.833333,0.500000,0.700000,1.600000,15
21,Equestrian Eventing,18.800000,29,32.966667,0.500000,0.766667,1.466667,15
22,Equestrian Jumping,23.466667,35,35.333333,0.500000,0.766667,1.466667,15
23,Fencing,39.000000,47,29.789444,0.473333,0.252759,5.200000,15
24,Football,18.533333,24,14.400000,1.000000,0.766667,1.466667,15
25,Golf,41.500000,42,60.000000,0.000000,0.750000,1.500000,2
26,Handball,16.461538,20,11.000000,1.000000,0.653846,1.692308,13
27,Hockey,13.800000,16,11.533333,1.000000,0.633333,1.733333,15
28,Judo,81.928571,135,26.184439,0.004762,0.264701,6.571429,14
29,Karate,35.000000,35,9.875000,0.000000,0.125000,8.000000,1
30,Kendo,2.000000,2,12.250000,0.000000,NaN,0.000000,1
31,Marathon Swimming,30.250000,33,25.250000,0.000000,0.625000,1.750000,4
32,Modern Pentathlon,23.000000,31,33.033333,0.266667,0.700000,1.600000,15
33,Rhythmic Gymnastics,21.800000,24,24.700000,0.350000,0.900000,1.200000,10
34,Roller Hockey,12.000000,12,12.000000,1.000000,NaN,0.000000,1
35,Rowing,45.200000,80,13.890476,0.857143,0.231973,7.600000,15
36,Rugby Sevens,15.000000,16,12.000000,1.000000,0.500000,2.000000,2
37,Sailing,55.333333,76,25.176212,0.641869,0.199545,6.266667,15
38,Shooting,81.066667,108,43.323594,0.013333,0.177840,7.800000,15
39,Skateboarding,25.000000,25,20.000000,0.000000,0.625000,2.000000,1
40,Softball,7.600000,8,7.600000,1.000000,1.000000,1.000000,5
41,Sport Climbing,19.000000,19,20.000000,0.000000,0.500000,2.000000,1
42,Surfing,18.000000,18,20.000000,0.000000,0.500000,2.000000,1
43,Swimming,104.933333,179,37.034170,0.183353,0.322874,8.066667,15
44,Table Tennis,51.444444,57,40.183333,0.511111,0.817840,1.444444,9
45,Taekwondo,53.625000,64,13.835938,0.000000,0.208333,4.500000,8
46,Tennis,43.727273,56,35.636364,0.490909,0.377284,2.727273,11
47,Trampolining,17.166667,20,15.333333,0.000000,0.666667,1.666667,6
48,Triathlon,37.166667,42,51.000000,0.055556,0.472222,2.166667,6
49,Volleyball,15.133333,19,10.533333,1.000000,0.566667,1.866667,15
50,Water Polo,13.333333,16,11.733333,1.000000,0.800000,1.400000,15
51,Waterskiing,17.000000,17,10.166667,0.000000,NaN,0.000000,1
52,Weightlifting,65.133333,92,19.241376,0.000000,0.284267,6.133333,15
53,Wrestling,55.733333,75,18.583426,0.000000,0.211307,8.600000,15
54,Wushu,42.000000,42,8.066667,0.000000,NaN,0.000000,1

Dataset sul successo olimpico

In [142]:
athletes_by_psy = df_clean.groupby(['country_noc', 'sport', 'year'])['athlete_id'].nunique().reset_index()
athletes_by_psy.columns = ['country_noc', 'sport', 'year', 'athletes_fielded']

gold_by_psy = (
    df_clean[df_clean['medal'] == 'Gold']
    .groupby(['country_noc', 'sport', 'year'])
    .size()
    .reset_index(name='golds_won')
)

success_df = athletes_by_psy.merge(gold_by_psy, on=['country_noc', 'sport', 'year'], how='left')
success_df['golds_won'] = success_df['golds_won'].fillna(0)
success_df['success_score'] = success_df['golds_won'] / success_df['athletes_fielded']

df_success_country_sport = success_df.groupby(['country_noc', 'sport']).agg(
    success_score_mean    = ('success_score',    'mean'),
    total_golds           = ('golds_won',        'sum'),
    total_athletes        = ('athletes_fielded', 'sum'),
).reset_index()
df_success_country_sport['success_score_overall'] = (
    df_success_country_sport['total_golds'] / df_success_country_sport['total_athletes']
)

df_success_country_sport.to_csv("Success_score_country_sport.csv", index=False)
df_success_country_sport

,country_noc,sport,success_score_mean,total_golds,total_athletes,success_score_overall
0,AFG,Athletics,0.000000,0.0,12,0.00
1,AFG,Boxing,0.000000,0.0,5,0.00
2,AFG,Judo,0.000000,0.0,3,0.00
3,AFG,Shooting,0.000000,0.0,1,0.00
4,AFG,Swimming,0.000000,0.0,1,0.00
...,...,...,...,...,...,...
3775,ZIM,Shooting,0.000000,0.0,17,0.00
3776,ZIM,Swimming,0.090909,2.0,25,0.08
3777,ZIM,Tennis,0.000000,0.0,13,0.00
3778,ZIM,Triathlon,0.000000,0.0,3,0.00
3779,ZIM,Weightlifting,0.000000,0.0,1,0.00

Dataset sui singoli eventi

In [143]:
event_year_rows = []

for (sport, event, year), grp in df_clean.groupby(['sport', 'event', 'year']):

    n_nations  = grp['country_noc'].nunique()
    n_athletes = grp['athlete_id'].nunique()
    is_team    = grp['isTeamSport'].iloc[0]

    medals = grp[grp['medal'].notna()]
    if len(medals) > 0:
        gold_by_country = medals[medals['medal'] == 'Gold'].groupby('country_noc').size()
        total_gold      = gold_by_country.sum()
        hhi             = ((gold_by_country / total_gold) ** 2).sum() if total_gold > 0 else np.nan
        n_nations_with_gold = gold_by_country.shape[0]
    else:
        hhi = np.nan
        n_nations_with_gold = 0

    event_year_rows.append({
        'sport':               sport,
        'event':               event,
        'year':                year,
        'n_nations':           n_nations,
        'n_athletes':          n_athletes,
        'is_team_event':       is_team,
        'hhi_gold':            hhi,
        'n_nations_with_gold': n_nations_with_gold,
    })

df_event_year = pd.DataFrame(event_year_rows)
df_event_year.to_csv("Event_features_by_year.csv", index=False)
df_event_year

,sport,event,year,n_nations,n_athletes,is_team_event,hhi_gold,n_nations_with_gold
0,3x3 Basketball,"3x3 Basketball, Men",2020,8,8,True,1.0,1
1,3x3 Basketball,"3x3 Basketball, Women",2020,8,8,True,1.0,1
2,Archery,"Individual, Men",1972,24,55,False,1.0,1
3,Archery,"Individual, Men",1976,23,37,False,1.0,1
4,Archery,"Individual, Men",1980,25,38,False,1.0,1
...,...,...,...,...,...,...,...,...
3872,Wushu,"Sanshou (≤60 kilograms), Women",2008,7,7,False,NaN,0
3873,Wushu,"Sanshou (≤70 kilograms), Men",2008,7,7,False,NaN,0
3874,Wushu,"Sanshou (≤85 kilograms), Men",2008,8,8,False,NaN,0
3875,Wushu,"Taijiquan & Taijijuan, Men",2008,8,8,False,NaN,0
3876,Wushu,"Taijiquan & Taijijuan, Women",2008,7,7,False,NaN,0

In [144]:
df_event_profile = df_event_year.groupby(['sport', 'event', 'is_team_event']).agg(
    n_nations_mean      = ('n_nations',           'mean'),
    n_nations_max       = ('n_nations',           'max'),
    n_athletes_mean     = ('n_athletes',          'mean'),
    hhi_gold_mean       = ('hhi_gold',            'mean'),
    n_nations_with_gold = ('n_nations_with_gold', 'mean'),
    n_editions          = ('year',                'nunique'),
).reset_index()

df_event_profile.to_csv("Event_profile_static.csv", index=False)

print(f"Totale eventi: {len(df_event_profile)}")
print(f"Eventi con 1 sola edizione: {(df_event_profile['n_editions'] == 1).sum()}")
print(f"Eventi con 5+ edizioni: {(df_event_profile['n_editions'] >= 5).sum()}")
df_event_profile

Totale eventi: 457
Eventi con 1 sola edizione: 71
Eventi con 5+ edizioni: 317

,sport,event,is_team_event,n_nations_mean,n_nations_max,n_athletes_mean,hhi_gold_mean,n_nations_with_gold,n_editions
0,3x3 Basketball,"3x3 Basketball, Men",True,8.000000,8,8.000000,1.0,1.0,1
1,3x3 Basketball,"3x3 Basketball, Women",True,8.000000,8,8.000000,1.0,1.0,1
2,Archery,"Individual, Men",False,32.769231,40,61.461538,1.0,1.0,13
3,Archery,"Individual, Women",False,29.615385,40,54.923077,1.0,1.0,13
4,Archery,"Team, Men",True,14.666667,22,14.666667,1.0,1.0,9
...,...,...,...,...,...,...,...,...,...
452,Wushu,"Sanshou (≤60 kilograms), Women",False,7.000000,7,7.000000,NaN,0.0,1
453,Wushu,"Sanshou (≤70 kilograms), Men",False,7.000000,7,7.000000,NaN,0.0,1
454,Wushu,"Sanshou (≤85 kilograms), Men",False,8.000000,8,8.000000,NaN,0.0,1
455,Wushu,"Taijiquan & Taijijuan, Men",False,8.000000,8,8.000000,NaN,0.0,1
456,Wushu,"Taijiquan & Taijijuan, Women",False,7.000000,7,7.000000,NaN,0.0,1