In [323]:
#Librerie
import pandas as pd
from warnings import filterwarnings
import numpy as np

In [324]:
filterwarnings('ignore')

In [325]:
#Dataset necessari
df_sport = pd.read_csv('Olympic_Athlete_Event_Details.csv')
df_socioec = pd.read_csv('dataset_olimpiadi_indicatori_ita.csv')
df_countries = pd.read_csv('Olympic_Country_Profiles.csv')

In [326]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
316829,2022 Winter Olympics,62,NED,Bobsleigh,"Monobob, Women",19019671,Karlien Sleper,148662,16,NaN,False
316830,2022 Winter Olympics,62,SVK,Bobsleigh,"Monobob, Women",19019671,Viktória Čerňanská,138683,17,NaN,False
316831,2022 Winter Olympics,62,KOR,Bobsleigh,"Monobob, Women",19019671,Kim Yu-Ran,137542,18,NaN,False
316832,2022 Winter Olympics,62,JAM,Bobsleigh,"Monobob, Women",19019671,Jazmine Fenlator-Victorian,128682,19,NaN,False
316833,2022 Winter Olympics,62,UKR,Bobsleigh,"Monobob, Women",19019671,Lidiya Hunko,149047,20,NaN,False

In [327]:
df_sport.shape

(316834, 11)

In [328]:
#Mantengo solo le edizioni estive
df_sport = df_sport[~df_sport['edition'].str.contains(r'Winter Olympics', case=False, na=False)]

In [329]:
df_sport.shape

(254981, 11)

In [330]:
len(df_sport['sport'].unique())

92

In [331]:
df_sport['sport'].unique()

array(['Athletics', 'Boxing', 'Diving', 'Rugby', 'Shooting', 'Swimming',
       'Rowing', 'Tennis', 'Artistic Gymnastics', 'Cycling Track',
       'Fencing', 'Wrestling', 'Art Competitions', 'Cycling Road',
       'Artistic Swimming', 'Judo', 'Sailing', 'Weightlifting',
       'Taekwondo', 'Archery', 'Golf', 'Canoe Sprint',
       'Cycling Mountain Bike', 'Modern Pentathlon', 'Handball',
       'Triathlon', 'Basketball', 'Roller Hockey', 'Beach Volleyball',
       'Hockey', 'Football', 'Badminton', 'Rhythmic Gymnastics',
       'Equestrian Jumping', 'Wushu', 'Canoe Slalom', 'Karate',
       'Table Tennis', 'Equestrian Eventing', 'Equestrian Dressage',
       'Volleyball', 'Trampolining', 'Marathon Swimming',
       'Cycling BMX Freestyle', 'Surfing', 'Baseball', 'Waterskiing',
       'Cycling BMX Racing', 'Rugby Sevens', 'Skateboarding',
       'Water Polo', 'Bowling', 'Softball', 'Sport Climbing',
       'Basque pelota', 'Gliding', 'Figure Skating', 'Polo',
       'Automobile Racing', 'Equestrian Driving', 'Equestrian Vaulting',
       'Ice Hockey', 'Tug-Of-War', 'Savate', 'Canoe Marathon',
       '3x3 Basketball', 'Glíma', 'Australian Rules Football',
       'Pesäpallo', 'Lacrosse', 'Firefighting', 'Bicycle Polo',
       'Alpinism', 'Kendo', 'Korfball', 'Kaatsen', 'Cricket',
       'Jeu De Paume', 'Motorboating', 'Racquets', 'Lifesaving',
       'Ballooning', 'Boules', 'Croquet', 'Fishing', 'Longue Paume',
       'Military Exercise', 'Motorcycle Sports', 'Canne De Combat',
       'Aeronautics', 'American Football', 'Roque'], dtype=object)

In [332]:
len(df_sport['event'].unique())

856

In [333]:
df_sport['event'].unique()

array(['100 metres, Men', '400 metres, Men', '800 metres, Men',
       '1,500 metres, Men', '5 miles, Men', 'Marathon, Men',
       '110 metres Hurdles, Men', '400 metres Hurdles, Men',
       '3,200 metres Steeplechase, Men', '3,500 metres Race Walk, Men',
       '10 miles Race Walk, Men', 'Standing High Jump, Men',
       'Long Jump, Men', 'Standing Long Jump, Men', 'Triple Jump, Men',
       'Lightweight, Men', 'Middleweight, Men', 'Springboard, Men',
       'Rugby, Men', 'Small-Bore Rifle, Prone, 50 and 100 yards, Men',
       'Small-Bore Rifle, Disappearing Target, 25 yards, Men',
       'Small-Bore Rifle, Moving Target, 25 yards, Men',
       '100 metres Freestyle, Men', '400 metres Freestyle, Men',
       '1,500 metres Freestyle, Men',
       '4 × 200 metres Freestyle Relay, Men',
       '100 metres Backstroke, Men', '200 metres Breaststroke, Men',
       '200 metres, Men', '5,000 metres, Men', '10,000 metres, Men',
       '10 kilometres Race Walk, Men', 'Cross-Country, Individual, Men',
       'Single Sculls, Men', 'Eights, Men',
       '400 metres Breaststroke, Men', '100 metres Freestyle, Women',
       'Singles, Covered Courts, Men', 'Individual All-Around, Men',
       'Standing Triple Jump, Men', 'Discus Throw, Men', 'Sprint, Men',
       'Sprint, Professionals, Men', 'Tandem Sprint, Professionals, Men',
       'Points Race, Professionals, Men',
       '3,000 metres, Handicap, Professionals, Men', 'Singles, Women',
       'Singles, Handicap, Women', 'Doubles, Mixed',
       'Doubles, Handicap, Mixed', 'Shot Put, Men',
       'Discus Throw, Greek Style, Men', 'Javelin Throw, Freestyle, Men',
       'Épée, Individual, Men', 'Épée, Team, Men',
       'Sabre, Individual, Men', 'Sabre, Team, Men',
       'Foil, Individual, Open', 'Singles, Men', 'Doubles, Men',
       'Lightweight, Greco-Roman, Men', 'Middleweight, Greco-Roman, Men',
       'Light-Heavyweight, Greco-Roman, Men', 'Sculpturing, Open',
       '4 × 100 metres Relay, Men', '4 × 400 metres Relay, Men',
       'Pole Vault, Men', 'Hammer Throw, Men', 'Pentathlon, Men',
       'Decathlon, Men', 'Road Race, Individual, Men',
       'Road Race, Team, Men', 'Foil, Individual, Men',
       'Doubles, Covered Courts, Men', 'Doubles, Covered Courts, Mixed',
       'Featherweight, Greco-Roman, Men',
       'Middleweight B, Greco-Roman, Men', 'Solo, Women', 'Duet, Women',
       '100 metres, Women', '200 metres, Women', 'Marathon, Women',
       'Light-Welterweight, Men', 'Light-Heavyweight, Men',
       'Windsurfer, Men', 'Half-Lightweight, Men',
       '50 metres Freestyle, Men', '50 metres Freestyle, Women',
       '100 metres Butterfly, Men', 'Middle-Heavyweight, Men',
       'Half-Middleweight, Men', '800 metres Freestyle, Women',
       'Super-Heavyweight, Men', 'One Person Dinghy, Women',
       'Multihull, Mixed', '200 metres Freestyle, Men',
       'Flyweight, Women', 'Air Pistol, 10 metres, Men',
       '100 metres Breaststroke, Men', 'Air Rifle, 10 metres, Women',
       'Long Jump, Women', 'Air Rifle, 10 metres, Men',
       'Small-Bore Rifle, Three Positions, 50 metres, Women',
       '100 metres Breaststroke, Women', 'Individual, Men',
       'Floor Exercise, Men', 'Parallel Bars, Men', 'Horizontal Bar, Men',
       'Individual, Women', 'Team, Mixed', 'Team, Men', 'Team, Women',
       'Extra-Lightweight, Men', 'Welterweight, Men',
       'Heavyweight II, Men', 'Heavyweight, Freestyle, Men',
       'Light-Middleweight, Men', 'Shot Put, Women',
       'Two Person Keelboat, Open', 'Light-Heavyweight, Freestyle, Men',
       'Hammer Throw, Women', 'Heavyweight, Men',
       'Half-Middleweight, Women', 'Half-Heavyweight, Men',
       'Two Person Dinghy, Men', '1,000 metres Time Trial, Men',
       'Individual Pursuit, 4,000 metres, Men', '400 metres, Women',
       '800 metres, Women', '1,500 metres, Women',
       '4 × 400 metres Relay, Women', 'Points Race, Men',
       'Bantamweight, Men', 'Windsurfer, Open', 'One Person Dinghy, Men',
       '4 × 100 metres Relay, Women',
       'Canadian Doubles, 1,000 metres, Men',
       'Kayak Singles, 500 metres, Women', 'Cross-Country, Men',
       'One Person Dinghy, Open', 'High Jump, Men', 'High Jump, Women',
       'Rapid-Fire Pistol, 25 metres, Men',
       'Small-Bore Rifle, Prone, 50 metres, Men', 'Trap, Open',
       '3,000 metres Steeplechase, Men', 'Flyweight, Men',
       'Featherweight, Men', 'Javelin Throw, Men',
       '100 kilometres Team Time Trial, Men',
       'Three Person Keelboat, Open', '5,000 metres, Women',
       '10,000 metres, Women', '3,000 metres Steeplechase, Women',
       'Welterweight, Freestyle, Men', '400 metres Hurdles, Women',
       'Handball, Men', 'Skeet, Women', 'Light-Flyweight, Men',
       '100 metres Hurdles, Women', 'Heptathlon, Women',
       'Small-Bore Rifle, Prone, 50 metres, Open',
       'Free Pistol, 50 metres, Open', 'Road Race, Individual, Women',
       'Triple Jump, Women', 'Kayak Singles, 200 metres, Men',
       'Kayak Singles, 1,000 metres, Men', '200 metres Butterfly, Men',
       '200 metres Individual Medley, Men',
       '400 metres Individual Medley, Men', 'Skeet, Open',
       'Horse Vault, Men', 'Rings, Men', 'Pommelled Horse, Men',
       'Skeet, Men', '200 metres Backstroke, Men',
       '400 metres Freestyle, Women', 'Olympic Distance, Men',
       '100 metres Backstroke, Women',
       'Sporting Pistol, 25 metres, Women', 'Javelin Throw, Women',
       'Air Pistol, 10 metres, Women', 'Lightweight, Freestyle, Men',
       'Lightweight, Women', 'Heavyweight, Greco-Roman, Men',
       'Half-Lightweight, Women', 'Free Pistol, 50 metres, Men',
       '100 metres Butterfly, Women', 'Featherweight, Women',
       '4 × 100 metres Medley Relay, Men', '3,000 metres, Women',
       'Basketball, Men', 'Roller Hockey, Men', 'Handball, Women',
       'Trap, Men', '200 metres Breaststroke, Women',
       'Middleweight, Women', 'Beach Volleyball, Men',
       'Canadian Singles, 500 metres, Men',
       'Canadian Singles, 1,000 metres, Men', 'Basketball, Women',
       'Canadian Singles, 200 metres, Men',
       'Lightweight Double Sculls, Men', 'Hockey, Men', 'Football, Men',
       'Flyweight, Freestyle, Men', 'Featherweight, Freestyle, Men',
       'Middleweight, Freestyle, Men', 'Bantamweight, Greco-Roman, Men',
       'Bantamweight, Freestyle, Men', 'Light-Flyweight, Freestyle, Men',
       'Platform, Men', 'Light-Flyweight, Greco-Roman, Men',
       '20 kilometres Race Walk, Women', 'Welterweight, Greco-Roman, Men',
       'Super-Heavyweight, Freestyle, Men', 'Sabre, Individual, Women',
       'Individual, Open', 'Group, Women',
       'Super-Heavyweight, Greco-Roman, Men',
       'Flyweight, Freestyle, Women', 'Lightweight, Freestyle, Women',
       'Middleweight, Freestyle, Women', 'Sanshou (≤56 kilograms), Men',
       'Sanshou (≤85 kilograms), Men', 'Individual Time Trial, Women',
       'Single Sculls, Women', 'Welterweight, Women',
       'Kayak Singles, Slalom, Men', 'Kayak Singles, 200 metres, Women',
       'Sprint, Women', 'Keirin, Women', 'Double Sculls, Men',
       'Featherweight, Freestyle, Women', 'Individual All-Around, Women',
       'Floor Exercise, Women', 'Horse Vault, Women',
       'Uneven Bars, Women', 'Balance Beam, Women',
       'Extra-Lightweight, Women', 'Heavyweight, Women',
       'Kumite, ≤67 kg, Men', 'Kumite, ≤75 kg, Men',
       'Kumite, >61 kg, Women', 'Light-Heavyweight, Freestyle, Women',
       'Springboard, Women',
       'Small-Bore Rifle, Three Positions, 50 metres, Men',
       'Heavyweight I, Men', 'Flyweight, Greco-Roman, Men',
       'Kayak Singles, 500 metres, Men', 'Sanshou (≤70 kilograms), Men',
       'Light-Heavyweight, Women', 'Super-Heavyweight, Women',
       'Half-Heavyweight, Women', 'Two Person Dinghy, Open',
       '10 kilometres Race Walk, Women', '200 metres Butterfly, Women',
       '200 metres Backstroke, Women', 'Windsurfer, Women',
       '200 metres Individual Medley, Women',
       'Kayak Singles, Slalom, Women', 'Canadian Singles, Slalom, Women',
       'Two Person Heavyweight Dinghy, Open', '5.5 metres, Open',
       'Multihull, Open', '4 × 100 metres Freestyle Relay, Men',
       'Two Person Keelboat, Men', 'Three Person Keelboat, Women',
       'Olympic Distance, Women', 'Skiff, Men',
       'Architecture, Further Entries, Open',
       '20 kilometres Race Walk, Men', '50 kilometres Race Walk, Men',
       '200 metres Freestyle, Women',
       'Military Rifle, Kneeling Or Standing, 300 metres, Men',
       'Volleyball, Men', 'Foil, Individual, Women',
       'Épée, Individual, Women', '400 metres Individual Medley, Women',
       'Doubles, Women', 'Volleyball, Women',
       'Individual Time Trial, Men', '10 kilometres Open Water, Women',
       'Discus Throw, Women', 'Pentathlon, Women',
       'Heavyweight, Freestyle, Women', 'Football, Women',
       'Team All-Around, Men', 'Team All-Around, Women',
       'Canadian Doubles, 500 metres, Men', 'Points Race, Women',
       'Coxless Pairs, Men', 'Quadruple Sculls, Men', 'Eights, Women',
       '4 × 100 metres Freestyle Relay, Women',
       '4 × 200 metres Freestyle Relay, Women',
       'Kayak Doubles, 500 metres, Women',
       'Kayak Fours, 500 metres, Women', 'Kayak Doubles, 500 metres, Men',
       'Kayak Fours, 1,000 metres, Men', '500 metres Time Trial, Women',
       'Coxless Pairs, Women', 'Quadruple Sculls, Women',
       'Running Target, 10 metres, Men', 'Coxless Fours, Men',
       'Pole Vault, Women', 'Kayak Doubles, 200 metres, Men',
       'Team Pursuit, Women', 'Omnium, Women', 'Double Sculls, Women',
       'Kayak Doubles, 1,000 metres, Men', 'Kayak Fours, 500 metres, Men',
       'Canadian Singles, 200 metres, Women',
       'Canadian Doubles, 500 metres, Women', 'Omnium, Men',
       'Lightweight Double Sculls, Women',
       'Air Rifle, 10 metres, Team, Mixed',
       '4 × 100 metres Medley Relay, Women',
       '4 × 100 metres Medley Relay, Mixed',
       'Small-Bore Rifle, Three Positions, 50 metres, Open',
       'Rapid-Fire Pistol, 25 metres, Open', 'Platform, Women',
       'Cross-Country, Women', 'Beach Volleyball, Women', 'Park, Men',
       'Shortboard, Men', 'Shortboard, Women', 'Unknown Event, Open',
       '80 metres Hurdles, Women', 'Individual Pursuit, Women',
       '800 metres Freestyle, Men',
       'Free Rifle, Three Positions, 300 metres, Open',
       'Running Target, 50 metres, Open', 'Open Class, Men',
       'Synchronized Platform, Women', 'Trap, Women', 'Baseball, Men',
       'Double Trap, Men', '4 × 400 metres Relay, Mixed', 'Music, Open',
       'Team Pursuit, 4,000 metres, Men', 'Foil, Team, Men',
       'Tandem Sprint, 2,000 metres, Men', 'Slalom, Men',
       'Running Target, 50 metres, Men', 'Team, Open', 'Madison, Men',
       'BMX, Men', 'Synchronized Platform, Men', 'BMX, Women',
       'Keirin, Men', 'Team Sprint, Women', 'Rugby Sevens, Women',
       'Street, Men', 'Finweight, Men', 'Canadian Singles, Slalom, Men',
       'Coxed Fours, Men', 'Water Polo, Men', 'Skiff, Open',
       'One Person Heavyweight Dinghy, Men', 'Two Person Dinghy, Women',
       'Kumite, >75 kg, Men', '10 kilometres Open Water, Men',
       'Free Rifle, Three Positions, 300 metres, Men', 'Finweight, Women',
       'Bantamweight, Women', 'Softball, Women', 'Double Trap, Women',
       'Daoshu & Gunshu, Men', 'Nanquan & Nangun, Men',
       'Taijiquan & Taijijuan, Men', 'Nanquan & Nandao, Women',
       'Jianshu & Qiangshu, Women', 'Taijiquan & Taijijuan, Women',
       'Kata, Men', 'Kumite, ≤55 kg, Women',
       'Dueling Pistol, 30 metres, Men',
       'Military Rifle, Three Positions, 300 metres, Men',
       'Military Rifle, Any Position, 600 metres, Men',
       '50 kilometres, Men', 'Coxed Pairs, Men',
       'Lightweight Coxless Fours, Men', 'Skiff, Women', 'Park, Women',
       '1,500 metres Freestyle, Women', 'Rugby Sevens, Men',
       'Canadian Doubles, Slalom, Men', 'Team Sprint, Men',
       'Combined, Men', 'Épée, Masters and Amateurs, Individual, Men',
       '6 metres, Open', 'Foil, Team, Women', 'Mano, Doubles, Men',
       'Mano, Singles, Men', 'Pala Corta, Doubles, Men',
       'Frontenis, Doubles, Men', 'Frontenis, Doubles, Women',
       'Épée, Team, Women', 'Synchronized Springboard, Men',
       'Air Pistol, 10 metres, Team, Mixed',
       '3,000 metres Race Walk, Men', 'Coxed Fours, Women',
       'Coxed Quadruple Sculls, Women', 'Painting, Graphic Arts, Open',
       'Painting, Paintings, Open', 'Gliding, Open',
       'Team Portable Apparatus, Women', 'Coxless Fours, Women',
       'Painting, Open', 'Sanshou (≤60 kilograms), Women',
       'Kumite, ≤61 kg, Women', 'Trap, Team, Mixed',
       'Foil, Masters, Individual, Men', 'Épée, Masters, Individual, Men',
       'Free Rifle, Prone, 600 metres, Men',
       'Free Rifle, 400, 600 and 800 metres, Team, Men', 'Polo, Men',
       '8 metres, Open', 'Paleta Cuero, Doubles, Men',
       'Paleta Goma, Doubles, Men', 'Tricks, Men', 'Hockey, Women',
       'Au Chapelet, 33 metres, Men', 'Au Chapelet, 50 metres, Men',
       'Au Cordon Doré, 33 metres, Men', 'Au Cordon Doré, 50 metres, Men',
       'Sur La Perche À La Herse, Men',
       'Sur La Perche À La Pyramide, Men', 'Championnat Du Monde, Men',
       '100 metres, Handicap, Men', '400 metres Hurdles, Handicap, Men',
       '400 metres, Professionals, Men',
       '1,500 metres, Professionals, Men',
       '6-hour race, Professionals, Men',
       '110 metres Hurdles, Professionals, Men',
       '2,500 metres Steeplechase, Professionals, Men',
       'Paris-Toulouse-Paris, Cars, Men',
       'Team Sprint, Professionals, Men',
       '50 kilometres, Professionals, Men',
       '100 kilometres, Professionals, Men',
       '100 miles, Professionals, Men', 'Hacks and Hunter Combined, Open',
       'Four-In-Hand Competition, Open', 'Long Jump, Open',
       'High Jump, Open', 'Sabre, Masters, Individual, Men',
       'Coxless Pairs, Boys', 'Coxless Fours, Boys', 'Eights, Boys',
       'Free Pistol, 50 metres, Team, Men',
       'Free Rifle, Three Positions, 300 metres, Team, Men',
       'Free Rifle, Kneeling, 300 metres, Men',
       'Free Rifle, Prone, 300 metres, Men',
       'Free Rifle, Standing, 300 metres, Men',
       '1,000 metres Freestyle, Men', '4,000 metres Freestyle, Men',
       '20 kilometres, Men', '100 kilometres, Men',
       'Free Pistol, 50 yards, Men', 'Free Pistol, 50 yards, Team, Men',
       'Coxed Fours, Outriggers, Men',
       'Target Archery, 28 metres, Individual, Men',
       'Target Archery, 33 metres, Individual, Men',
       'Target Archery, 50 metres, Individual, Men',
       'Target Archery, 28 metres, Team, Men',
       'Target Archery, 33 metres, Team, Men',
       'Target Archery, 50 metres, Team, Men',
       'Pole Archery, Small Birds, Individual, Men',
       'Pole Archery, Large Birds, Individual, Men',
       'Pole Archery, Small Birds, Team, Men',
       'Pole Archery, Large Birds, Team, Men', 'Literature, Open',
       'Team All-Around, Swedish System, Men', '3,000 metres, Team, Men',
       'Cross-Country, Team, Men', 'Plain High, Men', 'Pairs, Mixed',
       'Ice Hockey, Men', 'Military Pistol, Team, Men',
       'Military Rifle, Prone, 300 metres, Team, Men',
       'Military Rifle, Prone, 600 metres, Team, Men',
       'Military Rifle, Standing, 300 metres, Men',
       'Military Rifle, Standing, 300 metres, Team, Men',
       'Military Rifle, Prone, 300 and 600 metres, Team, Men',
       'Small-Bore Rifle, Standing, 50 metres, Men',
       'Smal-Bore Rifle, Standing, 50 metres, Team, Men',
       'Trap, Team, Men', 'Unknown Event, Men', 'Tug-Of-War, Men',
       'Plain High, Women', 'Savate, Men', 'Literature, Epic Works, Open',
       'Literature, Lyric Works, Open',
       'Music, Compositions For Orchestra, Open',
       'Music, Instrumental And Chamber, Open',
       'Painting, Drawings And Water Colors, Open',
       'Sculpturing, Medals And Reliefs, Open',
       'Sculpturing, Statues, Open',
       'Architecture, Designs For Town Planning, Open',
       'Painting, Unknown Event, Open',
       'Sculpturing, Unknown Event, Open', 'Sculpturing, Medals, Open',
       'Sculpturing, Reliefs, Open', 'Kayak Singles, 10,000 metres, Men',
       'Kayak Doubles, 10,000 metres, Men',
       'Folding Kayak Singles, 10,000 metres, Men',
       'Folding Kayak Doubles, 10,000 metres, Men',
       'Canadian Doubles, 10,000 metres, Men',
       'Kayak Relay, 4 × 500 metres, Men', '1,500 metres Wheelchair, Men',
       '3x3 Basketball, Men', 'Madison, Women', 'Street, Women',
       'Relay, Mixed', 'Changquan, Men', 'Jianshu & Qiangshu, Men',
       'Changquan, Women', 'Daoshu & Gunshu, Women', 'Kata, Women',
       'Military Pistol, 30 metres, Men', 'Architecture, Open',
       'Sanshou (≤52 kilograms), Women',
       'Synchronized Springboard, Women', 'Water Polo, Women',
       'Rope Climbing, Men', 'Side Horse, Men',
       'Running Target, Single Shot, Men',
       'Running Target, Single Shot, Team, Men',
       'Running Target, Double Shot, Men',
       'Running Target, Double Shot, Team, Men',
       'Literature, Dramatic Works, Open',
       'Music, Compositions For Solo Or Chorus, Open',
       'Painting, Applied Arts, Open',
       'Architecture, Architectural Designs, Open',
       'Music, Unknown Event, Open',
       'Sculpturing, Medals And Plaques, Open',
       'Canadian Singles, 10,000 metres, Men', 'Glíma, Men',
       'Free Pistol, 30 metres, Men', 'Military Pistol, 25 metres, Men',
       'Muzzle-Loading Pistol, 25 metres, Men',
       'Free Rifle, Any Position, 300 metres, Men',
       'Military Rifle, 200 metres, Men', '500 metres Freestyle, Men',
       '1,200 metres Freestyle, Men', 'Unlimited, One Hand, Men',
       'Unlimited, Two Hands, Men', '800 metres, Handicap, Men',
       '1,500 metres, Handicap, Men', 'Underwater Swimming, Men',
       'Military Rifle, 200/500/600/800/900/1,000 yards, Team, Men',
       'Team All-Around, Free System, Men', 'Coxed Fours, Inriggers, Men',
       'Military Rifle, 200, 400, 500 and 600 metres, Team, Men',
       'Small-Bore Rifle, Any Position, 50 metres, Men',
       'Small-Bore Rifle, Prone, 50 metres, Team, Men',
       'Small-Bore Rifle, Disappearing Target, 25 metres, Men',
       'Singles, Covered Courts, Women',
       'Middleweight A, Greco-Roman, Men',
       'Military Rifle, Prone, 300 metres, Men',
       'Military Rifle, Prone, 600 metres, Men',
       '800 metres Wheelchair, Women', '333⅓ metres Time Trial, Men',
       '12-Hours Race, Men', '2,500 metres Steeplechase, Men',
       '2,500 metres Steeplechase, Handicap, Men',
       '200 metres Obstacle Course, Men', 'Discus Throw, Both Hands, Men',
       'Combined, Women', 'Jumping, Men', '60 metres, Men',
       '200 metres Hurdles, Men', '110 metres Hurdles, Handicap, Men',
       'Parallel Bars, Teams, Men',
       '100 metres Freestyle For Sailors, Men',
       'Unlimited Class, Greco-Roman, Men',
       'Free Rifle, 1,000 yards, Men', 'Shot Put, Both Hands, Men',
       'Javelin Throw, Both Hands, Men',
       'Dueling Pistol, 30 metres, Team, Men',
       'Small-Bore Rifle, Disappearing Target, 25 metres, Team, Men',
       '100 metres, Professionals, Handicap, Men',
       '400 metres, Professionals, Handicap, Men',
       '100 yards, Handicap, Men', '120 yards Hurdles, Handicap, Men',
       '⅓ mile, Professionals, Men', '1 mile, Professionals, Men',
       'Australian Team Pursuit, Professionals, Men',
       '1 mile, Handicap, Professionals, Men',
       '2 miles, Handicap, Professionals, Men',
       '300 metres Freestyle, Women', 'Australian Rules Football, Men',
       'Running Target, Single and Double Shot, Men', 'Slalom, Women',
       'Tricks, Women', 'Jumping, Women', '10 metres, Open',
       '12 metres, Open', '56-pound Weight Throw, Men', 'Pesäpallo, Men',
       '3x3 Basketball, Women', 'Singles, Handicap, Men',
       'Doubles, Handicap, Men', 'Cesta Punta, Doubles, Men',

In [334]:
#Creo la colonna 'year'
df_sport.loc[:, 'year'] = df_sport['edition'].str.extract(r'(\d{4})').astype(int)

In [335]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False,1908
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False,1908
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False,1908
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False,1908
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False,1908
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [336]:
df_socioec

,Edizione_Olimpiadi,ID_Edizione,Anno,Nazione,Codice_NOC,Medaglie_Oro,Medaglie_Argento,Medaglie_Bronzo,Totale_Medaglie,Paese_Ospitante,...,RNL_Pro_Capite_USD,Iscrizioni_Scuola_Primaria_perc,Tasso_Mortalita_Neonatale,Tasso_Mortalita_Infantile,Aspettativa_di_Vita,Popolazione_Eta_Lavorativa_perc,Crescita_Demografica_perc,Popolazione_Totale,Popolazione_Urbana,Tasso_Urbanizzazione_perc
0,1964 Summer Olympics,16.0,1964.0,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964.0,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964.0,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964.0,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964.0,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020.0,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020.0,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020.0,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020.0,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020.0,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [337]:
df_socioec.columns

Index(['Edizione_Olimpiadi', 'ID_Edizione', 'Anno', 'Nazione', 'Codice_NOC',
       'Medaglie_Oro', 'Medaglie_Argento', 'Medaglie_Bronzo',
       'Totale_Medaglie', 'Paese_Ospitante', 'Citta_Ospitante',
       'Precipitazioni_Medie_mm', 'Superficie_Totale_km2',
       'Investimenti_Diretti_Esteri_perc_PIL', 'Densita_Popolazione',
       'Inflazione_Prezzi_Consumo', 'Spesa_Militare_Valuta_Locale',
       'Spesa_Militare_perc_PIL', 'Spesa_Pubblica_Consumi_USD',
       'Spesa_Nazionale_Lorda_Valuta_Locale',
       'Interscambio_Commerciale_perc_PIL',
       'Valore_Aggiunto_Industria_perc_PIL',
       'Valore_Aggiunto_Servizi_Valuta_Locale',
       'Valore_Aggiunto_Servizi_perc_PIL', 'Inflazione_Deflatore_PIL',
       'PIL_Assoluto_USD', 'PIL_Valuta_Locale', 'Crescita_PIL_perc_annua',
       'PIL_Pro_Capite_USD', 'RNL_Valuta_Locale', 'RNL_Pro_Capite_USD',
       'Iscrizioni_Scuola_Primaria_perc', 'Tasso_Mortalita_Neonatale',
       'Tasso_Mortalita_Infantile', 'Aspettativa_di_Vita',
       'Popolazione_Eta_Lavorativa_perc', 'Crescita_Demografica_perc',
       'Popolazione_Totale', 'Popolazione_Urbana',
       'Tasso_Urbanizzazione_perc'],
      dtype='object')

In [338]:
#Rinomino colonne per favorire il merge
mapping_socioec = {
    'Edizione_Olimpiadi': 'edition',
    'ID_Edizione': 'edition_id',
    'Anno': 'year',
    'Nazione': 'country',
    'Codice_NOC': 'country_noc',
    'Medaglie_Oro': 'gold',
    'Medaglie_Argento': 'silver',
    'Medaglie_Bronzo': 'bronze',
    'Totale_Medaglie': 'total',
    #'Popolazione_Totale': 'population'
}

In [339]:
df_socioec =df_socioec.rename(columns=mapping_socioec)

In [340]:
df_socioec

,edition,edition_id,year,country,country_noc,gold,silver,bronze,total,Paese_Ospitante,...,RNL_Pro_Capite_USD,Iscrizioni_Scuola_Primaria_perc,Tasso_Mortalita_Neonatale,Tasso_Mortalita_Infantile,Aspettativa_di_Vita,Popolazione_Eta_Lavorativa_perc,Crescita_Demografica_perc,Popolazione_Totale,Popolazione_Urbana,Tasso_Urbanizzazione_perc
0,1964 Summer Olympics,16.0,1964.0,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964.0,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964.0,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964.0,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964.0,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020.0,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020.0,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020.0,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020.0,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020.0,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [341]:
#Trasformo l'anno in intero
df_socioec['year'] = df_socioec[('year')].astype(int)
df_socioec

,edition,edition_id,year,country,country_noc,gold,silver,bronze,total,Paese_Ospitante,...,RNL_Pro_Capite_USD,Iscrizioni_Scuola_Primaria_perc,Tasso_Mortalita_Neonatale,Tasso_Mortalita_Infantile,Aspettativa_di_Vita,Popolazione_Eta_Lavorativa_perc,Crescita_Demografica_perc,Popolazione_Totale,Popolazione_Urbana,Tasso_Urbanizzazione_perc
0,1964 Summer Olympics,16.0,1964,United States,USA,36.0,26.0,28.0,90.0,JPN,...,3325.0,NaN,NaN,25.200,70.019512,59.769954,1.544964,1.850355e+08,1.308124e+08,70.686700
1,1964 Summer Olympics,16.0,1964,Soviet Union,RUS,30.0,31.0,35.0,96.0,JPN,...,NaN,NaN,NaN,32.975,67.820573,63.134321,1.110863,1.219210e+08,6.767589e+07,55.495898
2,1964 Summer Olympics,16.0,1964,Japan,JPN,16.0,5.0,8.0,29.0,JPN,...,695.0,NaN,NaN,26.700,68.598720,65.650277,0.946220,9.452600e+07,6.119483e+07,64.727269
3,1964 Summer Olympics,16.0,1964,Germany,GER,10.0,22.0,18.0,50.0,JPN,...,1425.0,NaN,NaN,NaN,69.605561,66.372495,0.858387,7.373317e+07,5.636501e+07,76.439154
4,1964 Summer Olympics,16.0,1964,Italy,ITA,10.0,10.0,7.0,27.0,JPN,...,1060.0,NaN,23.325,41.700,69.320488,65.477136,0.691520,5.071688e+07,3.046761e+07,60.069421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3363,2020 Summer Olympics,61.0,2020,"Iran, Islamic Republic of",IRN,0.0,0.0,0.0,0.0,JPN,...,5317.5,105.547544,9.100,12.800,76.506750,69.484625,1.306438,8.550216e+07,6.376662e+07,74.572028
3364,2020 Summer Olympics,61.0,2020,"Netherlands, Kingdom of the",NLD,0.0,0.0,0.0,0.0,JPN,...,49475.0,104.964952,2.600,3.500,81.811585,65.311345,0.590597,1.718453e+07,1.581978e+07,92.049586
3365,2020 Summer Olympics,61.0,2020,"Korea, Democratic People's Republic of",PRK,0.0,0.0,0.0,0.0,JPN,...,NaN,92.064842,10.150,15.250,72.988250,69.770014,0.447847,2.587120e+07,1.602924e+07,61.956394
3366,2020 Summer Olympics,61.0,2020,"Palestine, State of",PSE,0.0,0.0,0.0,0.0,JPN,...,4055.0,96.563815,10.600,14.375,75.331000,56.914064,2.319896,4.519072e+06,3.864753e+06,85.516174
3367,2020 Summer Olympics,61.0,2020,"Tanzania, United Republic of",TZA,0.0,0.0,0.0,0.0,JPN,...,995.0,91.876625,23.125,36.800,65.215500,53.139620,3.221264,5.652223e+07,1.841442e+07,32.558175

In [342]:
df_sport.shape

(254981, 12)

In [343]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,NaN,False,1908
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,NaN,False,1908
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,NaN,False,1908
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,NaN,False,1908
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,NaN,False,1908
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [344]:
#Mantengo solo le edizioni olimpiche che si sono tenute negli anni presenti nel dataset degli indicatori socioeconomici
years_ok = df_socioec['year'].unique()
df_sport = df_sport.loc[df_sport['year'].isin(years_ok)]

In [345]:
df_sport.shape

(179141, 12)

In [346]:
df_sport

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year
363,1988 Summer Olympics,22,ARU,Artistic Swimming,"Solo, Women",43507,Roswitha Lopez,44994,18,NaN,False,1988
364,1988 Summer Olympics,22,ARU,Artistic Swimming,"Solo, Women",43507,Yvette Thuis,44995,AC r1/3,NaN,False,1988
365,1988 Summer Olympics,22,ARU,Artistic Swimming,"Duet, Women",43511,Yvette Thuis,44995,15,NaN,True,1988
366,1988 Summer Olympics,22,ARU,Artistic Swimming,"Duet, Women",43511,Roswitha Lopez,44994,15,NaN,True,1988
367,1988 Summer Olympics,22,ARU,Athletics,"100 metres, Women",63682,Evelyn Farrell,64471,8 h7 r1/4,NaN,False,1988
...,...,...,...,...,...,...,...,...,...,...,...,...
316416,2020 Summer Olympics,61,USA,Wrestling,"Featherweight, Freestyle, Women",19009677,Jacarra Winchester,147307,=5,NaN,False,2020
316417,2020 Summer Olympics,61,USA,Wrestling,"Lightweight, Freestyle, Women",19009706,Helen Maroulis,132194,=3,Bronze,False,2020
316418,2020 Summer Olympics,61,USA,Wrestling,"Middleweight, Freestyle, Women",19009735,Kayla Miracle,147308,12,NaN,False,2020
316419,2020 Summer Olympics,61,USA,Wrestling,"Light-Heavyweight, Freestyle, Women",19009764,Tamyra Mensah-Stock,147310,1,Gold,False,2020
316420,2020 Summer Olympics,61,USA,Wrestling,"Heavyweight, Freestyle, Women",19009793,Adeline Gray,132192,2,Silver,False,2020

In [347]:
df_sport['year'].unique()

array([1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 1984, 1976,
       1972, 1980, 1968, 1964])

In [348]:
df_socioec['year'].unique()

array([1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004,
       2008, 2012, 2016, 2020])

In [349]:
df_socioec['country'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'The Bahamas', 'Republic of Korea', 'Trinidad and Tobago',
       'Tunisia', 'Argentina', 'Cuba', 'Pakistan', 'Philippines',
       'Islamic Republic of Iran', 'Brazil', 'Ghana', 'Ireland', 'Kenya',
       'Mexico', 'Nigeria', 'Uruguay', 'East Germany', 'West Germany',
       'Norway', 'Venezuela', 'Austria', 'Mongolia', 'Uganda', 'Cameroon',
       'Jamaica', 'Chinese Taipei', 'Greece',
       "Democratic People's Republic of Korea", 'Colombia', 'Lebanon',
       'Niger', 'Spain', 'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand',
       'Zimbabwe', 'United Republic of Tanzania', 'Guyana',
       "People's Republic of China", 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Republic of Moldova',
       'Uzbekistan', 'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique',
       'Kingdom of Saudi Arabia', 'Sri Lanka', 'Vietnam', 'Barbados',
       'Kuwait', 'Kyrgyzstan', 'North Macedonia', 'United Arab Emirates',
       'Paraguay', 'Eritrea', 'Panama', 'Serbia', 'Tajikistan', 'Samoa',
       'Singapore', 'Sudan', 'Afghanistan', 'Mauritius', 'Togo',
       'Bahrain', 'Grenada', 'Botswana', 'Cyprus', 'Gabon', 'Guatemala',
       'Montenegro', 'Fiji', 'Jordan', 'Kosovo', 'ROC', 'San Marino',
       'Turkmenistan', 'Burkina Faso', 'Aruba', 'Angola', 'Albania',
       'Andorra', 'American Samoa', 'Antigua and Barbuda', 'Benin',
       'Bangladesh', 'Bahamas', 'Bosnia and Herzegovina', 'Belize',
       'Brunei Darussalam', 'Bhutan', 'Central African Republic', 'China',
       'Congo', 'Comoros', 'Cabo Verde', 'Cayman Islands', 'Dominica',
       'Guinea', 'Gambia', 'Guinea-Bissau', 'Equatorial Guinea',
       'Greenland', 'Guam', 'Hong Kong', 'Honduras', 'Haiti', 'Iraq',
       'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'Somalia', 'South Sudan',
       'Sao Tome and Principe', 'Eswatini', 'Seychelles', 'Chad',
       'Timor-Leste', 'Tuvalu', 'Saint Vincent and the Grenadines',
       'Virgin Islands (U.S.)', 'Viet Nam', 'Vanuatu', 'Yemen',
       'United States of America', 'Hong Kong, China',
       'Bolivia, Plurinational State of',
       'Congo, Democratic Republic of the',
       'Micronesia, Federated States of', 'Iran, Islamic Republic of',
       'Moldova, Republic of', 'Netherlands, Kingdom of the',
       "Korea, Democratic People's Republic of", 'Palestine, State of',
       'Tanzania, United Republic of',
       'Venezuela, Bolivarian Republic of', 'Korea, Republic of'],
      dtype=object)

In [350]:
#Riduco le varianti dei nomi dei vari Paesi ad un nome unico per Pese
mapping_varianti = {
    'Iran, Islamic Republic of': 'Iran',
    'Islamic Republic of Iran': 'Iran',
    'Tanzania, United Republic of': 'Tanzania',
    'United Republic of Tanzania': 'Tanzania',
    'Moldova, Republic of': 'Moldova',
    'Republic of Moldova': 'Moldova',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
    'The Bahamas': 'Bahamas',
    'Korea, Republic of': 'South Korea',
    'Republic of Korea': 'South Korea',
    "Korea, Democratic People's Republic of": 'North Korea',
    "Democratic People's Republic of Korea": 'North Korea',
    "People's Republic of China": 'China',
    'Hong Kong, China': 'Hong Kong',
    'United States of America': 'United States',
    'Kingdom of Saudi Arabia': 'Saudi Arabia',
    'Palestine, State of': 'Palestine',
    'Virgin Islands (U.S.)': 'United States Virgin Islands',
    'United States Virgin Islands': 'United States Virgin Islands',
    'Micronesia, Federated States of': 'Federated States of Micronesia',
    'Netherlands, Kingdom of the': 'Kingdom of the Netherlands',
    'Bolivia, Plurinational State of': 'Plurinational State of Bolivia'
}

In [351]:
#mapping_speciali = {
    #"Independent Olympic Athletes": "Independent"???,
    #"ROC": "Russia"--> Russia che non può gareggiare come russia ma come comitato olimpico,
#    'Virgin Islands (U.S.)': 'United States Virgin Islands',
#    'United States Virgin Islands': 'United States Virgin Islands'
#}

In [352]:
country_mapping = {
    **mapping_varianti,
    #**mapping_speciali
}

In [353]:
#Applico la riduzione delle varianti dei nomi dei Paesi al dataset
df_socioec["country"] = df_socioec["country"].replace(country_mapping)

In [354]:
df_socioec['country'].unique()

array(['United States', 'Soviet Union', 'Japan', 'Germany', 'Italy',
       'Hungary', 'Poland', 'Australia', 'Czechoslovakia',
       'Great Britain', 'Bulgaria', 'Finland', 'New Zealand', 'Romania',
       'Netherlands', 'Türkiye', 'Sweden', 'Denmark', 'Yugoslavia',
       'Belgium', 'France', 'Canada', 'Switzerland', 'Ethiopia', 'India',
       'Bahamas', 'South Korea', 'Trinidad and Tobago', 'Tunisia',
       'Argentina', 'Cuba', 'Pakistan', 'Philippines', 'Iran', 'Brazil',
       'Ghana', 'Ireland', 'Kenya', 'Mexico', 'Nigeria', 'Uruguay',
       'East Germany', 'West Germany', 'Norway', 'Venezuela', 'Austria',
       'Mongolia', 'Uganda', 'Cameroon', 'Jamaica', 'Chinese Taipei',
       'Greece', 'North Korea', 'Colombia', 'Lebanon', 'Niger', 'Spain',
       'Portugal', 'Bermuda', 'Puerto Rico', 'Thailand', 'Zimbabwe',
       'Tanzania', 'Guyana', 'China', 'Morocco', "Côte d'Ivoire", 'Egypt',
       'Peru', 'Syrian Arab Republic', 'Algeria', 'Dominican Republic',
       'Iceland', 'Zambia', 'Suriname', 'Chile', 'Costa Rica',
       'Indonesia', 'Netherlands Antilles', 'Senegal',
       'United States Virgin Islands', 'Djibouti', 'Unified Team',
       'Estonia', 'Lithuania', 'Latvia', 'Namibia', 'South Africa',
       'Croatia', 'Independent Olympic Athletes', 'Israel', 'Slovenia',
       'Malaysia', 'Qatar', 'Russian Federation', 'Ukraine', 'Czechia',
       'Kazakhstan', 'Belarus', 'Serbia and Montenegro', 'Slovakia',
       'Armenia', 'Burundi', 'Ecuador', 'Moldova', 'Uzbekistan',
       'Azerbaijan', 'Tonga', 'Georgia', 'Mozambique', 'Saudi Arabia',
       'Sri Lanka', 'Vietnam', 'Barbados', 'Kuwait', 'Kyrgyzstan',
       'North Macedonia', 'United Arab Emirates', 'Paraguay', 'Eritrea',
       'Panama', 'Serbia', 'Tajikistan', 'Samoa', 'Singapore', 'Sudan',
       'Afghanistan', 'Mauritius', 'Togo', 'Bahrain', 'Grenada',
       'Botswana', 'Cyprus', 'Gabon', 'Guatemala', 'Montenegro', 'Fiji',
       'Jordan', 'Kosovo', 'ROC', 'San Marino', 'Turkmenistan',
       'Burkina Faso', 'Aruba', 'Angola', 'Albania', 'Andorra',
       'American Samoa', 'Antigua and Barbuda', 'Benin', 'Bangladesh',
       'Bosnia and Herzegovina', 'Belize', 'Brunei Darussalam', 'Bhutan',
       'Central African Republic', 'Congo', 'Comoros', 'Cabo Verde',
       'Cayman Islands', 'Dominica', 'Guinea', 'Gambia', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greenland', 'Guam', 'Hong Kong', 'Honduras',
       'Haiti', 'Iraq', 'Cambodia', 'Kiribati', 'Saint Kitts and Nevis',
       "Lao People's Democratic Republic", 'Liberia', 'Libya',
       'Saint Lucia', 'Liechtenstein', 'Lesotho', 'Luxembourg', 'Macao',
       'Monaco', 'Madagascar', 'Maldives', 'Marshall Islands', 'Mali',
       'Malta', 'Myanmar', 'Mauritania', 'Malawi', 'New Caledonia',
       'Nicaragua', 'Nepal', 'Nauru', 'Oman', 'Palau', 'Papua New Guinea',
       'French Polynesia', 'Rwanda', 'Solomon Islands', 'Sierra Leone',
       'El Salvador', 'Somalia', 'South Sudan', 'Sao Tome and Principe',
       'Eswatini', 'Seychelles', 'Chad', 'Timor-Leste', 'Tuvalu',
       'Saint Vincent and the Grenadines', 'Vanuatu', 'Yemen',
       'Plurinational State of Bolivia',
       'Democratic Republic of the Congo',
       'Federated States of Micronesia', 'Kingdom of the Netherlands',
       'Palestine'], dtype=object)

In [355]:
noc_atleti = df_sport["country_noc"].unique()

In [356]:
paesi_socio = df_socioec["country_noc"].unique()

In [357]:
#Individuo i NOC dei Paesi che non corrispondono tra i due dataset
set(noc_atleti) - set(paesi_socio)

{'ANG',
 'ANT',
 'ARU',
 'ASA',
 'BAN',
 'BHU',
 'BIZ',
 'BRU',
 'CAM',
 'CAY',
 'CGO',
 'CHA',
 'COK',
 'EOR',
 'ESA',
 'GAM',
 'GBS',
 'GEQ',
 'GUI',
 'HAI',
 'HON',
 'IVB',
 'LBA',
 'LES',
 'MAD',
 'MAW',
 'MON',
 'MTN',
 'MYA',
 'NCA',
 'NEP',
 'OMA',
 'PLE',
 'SEY',
 'SKN',
 'SOL',
 'URS',
 'VAN',
 'VIN',
 'YAR',
 'YMD'}

In [358]:
len(set(noc_atleti) - set(paesi_socio))

41

In [359]:
#Allineo i country_noc dei due dataset
mapping_noc = {
    'Angola': 'ANG',
    'Antigua and Barbuda': 'ANT',
    'Aruba': 'ARU',
    'American Samoa': 'ASA',
    'Bangladesh': 'BAN',
    'Bhutan': 'BHU',
    'Belize': 'BIZ',
    'Brunei Darussalam': 'BRU',
    'Cambodia': 'CAM',
    'Cayman Islands': 'CAY',
    'Congo': 'CGO',
    'Chad': 'CHA',
    'El Salvador': 'ESA',
    'Gambia': 'GAM',
    'Guinea-Bissau': 'GBS',
    'Equatorial Guinea': 'GEQ',
    'Guinea': 'GUI',
    'Haiti': 'HAI',
    'Honduras': 'HON',
    'Libya': 'LBA',
    'Lesotho': 'LES',
    'Madagascar': 'MAD',
    'Malawi': 'MAW',
    'Monaco': 'MON',
    'Mauritania': 'MTN',
    'Myanmar': 'MYA',
    'Nicaragua': 'NCA',
    'Nepal': 'NEP',
    'Oman': 'OMA',
    'Palestine': 'PLE',
    'Seychelles': 'SEY',
    'Saint Kitts and Nevis': 'SKN',
    'Solomon Islands': 'SOL',
    'Soviet Union': 'URS',
    'Vanuatu': 'VAN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Democratic Republic of the Congo' :'COD',
    'Russian Olympic Committee': 'ROC'
}

In [360]:
#Applico la modifica
mask = df_socioec["country"].isin(mapping_noc.keys())

df_socioec.loc[mask, "country_noc"] = df_socioec.loc[mask, "country"].map(mapping_noc)

In [361]:
#Controllo quali sono i paesi che non hanno mai vinto una medaglia
all_nocs = set(df_sport['country_noc'])
nocs_with_medals = set(df_sport[df_sport['medal'].notna()]['country_noc'])
no_medals = all_nocs - nocs_with_medals
no_medals

{'ALB',
 'AND',
 'ANG',
 'ANT',
 'ARU',
 'ASA',
 'BAN',
 'BEN',
 'BHU',
 'BIH',
 'BIZ',
 'BOL',
 'BRU',
 'CAF',
 'CAM',
 'CAY',
 'CGO',
 'CHA',
 'COD',
 'COK',
 'COM',
 'CPV',
 'DMA',
 'EOR',
 'ESA',
 'FSM',
 'GAM',
 'GBS',
 'GEQ',
 'GUI',
 'GUM',
 'HAI',
 'HON',
 'IRQ',
 'IVB',
 'KIR',
 'LAO',
 'LBA',
 'LBR',
 'LCA',
 'LES',
 'LIE',
 'LUX',
 'MAD',
 'MAW',
 'MDV',
 'MHL',
 'MLI',
 'MLT',
 'MON',
 'MTN',
 'MYA',
 'NCA',
 'NEP',
 'NRU',
 'OMA',
 'PLE',
 'PLW',
 'PNG',
 'RWA',
 'SEY',
 'SKN',
 'SLE',
 'SOL',
 'SOM',
 'SSD',
 'STP',
 'SWZ',
 'TLS',
 'TUV',
 'VAN',
 'VIN',
 'VNM',
 'YAR',
 'YEM',
 'YMD'}

In [362]:
len(no_medals)

76

In [363]:
len(df_sport['country_noc'].unique())

220

In [364]:
#Elimino dal dataset i Paesi che non hanno mai vinto una medaglia
df_sport = df_sport[~df_sport['country_noc'].isin(no_medals)]

In [365]:
len(df_sport['country_noc'].unique())

144

In [366]:
#Calcolo il numero di atleti per ogni anno, paese e sport
num_athl = df_sport.groupby(['year', 'country_noc', 'sport'])['athlete_id'].nunique().reset_index()
num_athl = num_athl.rename(columns={'athlete_id': 'num_athletes'})

In [367]:
#Ai fini del cacolo delle medaglie per i paesi, riduco le righe di sport di squadra in base ad anno, country_noc, evento specifico e tipo di medaglia, in modo da non falsare il calcolo in base alle medaglie degli sport di squadra
team_rows = df_sport[df_sport['isTeamSport'] == True]
ind_rows  = df_sport[df_sport['isTeamSport'] == False]

team_reduct = team_rows.drop_duplicates(subset=['year', 'country_noc', 'event', 'medal'])
df_clean = pd.concat([ind_rows, team_reduct], ignore_index=True)

print(f"Righe originali: {len(df_sport):,}")
print(f"Righe dopo la riduzione di quelle degli sport di squadra: {len(df_clean):,}")

Righe originali: 173,603
Righe dopo la riduzione di quelle degli sport di squadra: 116,230

In [368]:
#Aggiungo la colonna con l'informazione sul numero di atleti
df_clean = df_clean.merge(num_athl, on=['year', 'country_noc', 'sport'], how='left')

In [369]:
df_socioec.columns

Index(['edition', 'edition_id', 'year', 'country', 'country_noc', 'gold',
       'silver', 'bronze', 'total', 'Paese_Ospitante', 'Citta_Ospitante',
       'Precipitazioni_Medie_mm', 'Superficie_Totale_km2',
       'Investimenti_Diretti_Esteri_perc_PIL', 'Densita_Popolazione',
       'Inflazione_Prezzi_Consumo', 'Spesa_Militare_Valuta_Locale',
       'Spesa_Militare_perc_PIL', 'Spesa_Pubblica_Consumi_USD',
       'Spesa_Nazionale_Lorda_Valuta_Locale',
       'Interscambio_Commerciale_perc_PIL',
       'Valore_Aggiunto_Industria_perc_PIL',
       'Valore_Aggiunto_Servizi_Valuta_Locale',
       'Valore_Aggiunto_Servizi_perc_PIL', 'Inflazione_Deflatore_PIL',
       'PIL_Assoluto_USD', 'PIL_Valuta_Locale', 'Crescita_PIL_perc_annua',
       'PIL_Pro_Capite_USD', 'RNL_Valuta_Locale', 'RNL_Pro_Capite_USD',
       'Iscrizioni_Scuola_Primaria_perc', 'Tasso_Mortalita_Neonatale',
       'Tasso_Mortalita_Infantile', 'Aspettativa_di_Vita',
       'Popolazione_Eta_Lavorativa_perc', 'Crescita_Demografica_perc',
       'Popolazione_Totale', 'Popolazione_Urbana',
       'Tasso_Urbanizzazione_perc'],
      dtype='object')

In [370]:
#Aggiungo la colonna sulla popolazione dei paesi sul dataset sa cui verranno generati gli altri
#df_clean = df_clean.merge(df_socioec[['year', 'country_noc', 'population']], on=['year', 'country_noc'], how='left')

In [371]:
#df_clean

In [372]:
#nan_pop = df_clean[df_clean['population'].isna()][['year', 'country_noc']].drop_duplicates()
#print(f"Anno e paese senza dati su popolazione: {len(nan_pop):,}")
#nan_pop

In [373]:
#print(f"Paesi unici senza dati popolazione: {nan_pop['country_noc'].nunique()}")
#print(nan_pop['country_noc'].unique())

In [374]:
#print(f"Anni unici senza dati popolazione: {nan_pop['year'].nunique()}")
#print(sorted(nan_pop['year'].unique()))

In [375]:
#nan_pop.groupby('country_noc').size().sort_values(ascending=False)

In [376]:
#Funzione per calcolare il tipo e il numero di medaglie
def medals(group):
    return pd.Series({
        'gold':   (group['medal'] == 'Gold').sum(),
        'silver': (group['medal'] == 'Silver').sum(),
        'bronze': (group['medal'] == 'Bronze').sum(),
    })

## Dataset "Macro_sport"

In [377]:
#Creo il DataFrame "Macro_sport" che contiene, per ogni olimpiade:
# - country_noc: codice noc dei paesi,
# - country: i nomi estesi dei paesi partecipanti
# - year: l'anno dell'olimpiade
# - sport: la categoria sportiva
# - num_athletes: il numero di atleti partecipanti in ogni categoria sportiva per paese e anno
# - old, silver, bronze: il numero di medaglie d'oro, di bronzo, d'argento
# - total_medals: il numero di medaglie totali
# - gold_per_athletes: medaglie d'oro per numero di atleti partecipanti
# - tot_med_per_athletes: medaglie totali per numero di atleti partecipanti

df_macro_sport = df_clean.groupby(['country_noc', 'year', 'sport', 'num_athletes']).apply(
    medals
).reset_index()

df_macro_sport['total_medals'] = (df_macro_sport['gold'] + df_macro_sport['silver'] + df_macro_sport['bronze'])
df_macro_sport['gold_per_athletes'] = df_macro_sport['gold'] / df_macro_sport['num_athletes']
df_macro_sport['tot_med_per_athletes'] = df_macro_sport['total_medals'] / df_macro_sport['num_athletes']
df_macro_sport

,country_noc,year,sport,num_athletes,gold,silver,bronze,total_medals,gold_per_athletes,tot_med_per_athletes
0,AFG,1964,Wrestling,8,0,0,0,0,0.0,0.0
1,AFG,1968,Wrestling,5,0,0,0,0,0.0,0.0
2,AFG,1972,Wrestling,8,0,0,0,0,0.0,0.0
3,AFG,1980,Boxing,3,0,0,0,0,0.0,0.0
4,AFG,1980,Wrestling,8,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
18958,ZIM,2016,Swimming,2,0,0,0,0,0.0,0.0
18959,ZIM,2020,Athletics,1,0,0,0,0,0.0,0.0
18960,ZIM,2020,Golf,1,0,0,0,0,0.0,0.0
18961,ZIM,2020,Rowing,1,0,0,0,0,0.0,0.0
18962,ZIM,2020,Swimming,2,0,0,0,0,0.0,0.0

In [378]:
#Aggiungo al DataFrame il nome esteso del paese e salvo come dataset da usare in analisi successive
df_countries = df_countries.rename(columns={'noc': 'country_noc'})
df_countries['country'] = df_countries['country'].replace(country_mapping)
df_macro_sport = df_macro_sport.merge(df_countries, on='country_noc', how='left')
cols = list(df_macro_sport.columns)
cols.insert(cols.index('country_noc') + 1, cols.pop(cols.index('country')))
df_macro_sport = df_macro_sport[cols]
df_macro_sport = df_macro_sport.sort_values('country', key=lambda x: x.str.len(), ascending=False)
df_macro_sport = df_macro_sport.drop_duplicates(subset=['country_noc', 'year', 'sport'], keep='first')
df_macro_sport.to_csv("Macro_sports.csv", index=False)
df_macro_sport

,country_noc,country,year,sport,num_athletes,gold,silver,bronze,total_medals,gold_per_athletes,tot_med_per_athletes
8676,IOA,Independent Olympic Athletes,1992,Shooting,8,0,1,2,3,0.0,0.375
8668,IOA,Independent Olympic Athletes,1992,Canoe Slalom,3,0,0,0,0,0.0,0.000
8683,IOA,Independent Olympic Athletes,2000,Weightlifting,1,0,0,0,0,0.0,0.000
8682,IOA,Independent Olympic Athletes,2000,Boxing,1,0,0,0,0,0.0,0.000
9251,ISV,United States Virgin Islands,1976,Wrestling,4,0,0,0,0,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...
16896,TOG,Togo,2008,Tennis,1,0,0,0,0,0.0,0.000
16897,TOG,Togo,2012,Athletics,2,0,0,0,0,0.0,0.000
16898,TOG,Togo,2012,Canoe Slalom,1,0,0,0,0,0.0,0.000
16899,TOG,Togo,2012,Judo,1,0,0,0,0,0.0,0.000
16900,TOG,Togo,2012,Swimming,1,0,0,0,0,0.0,0.000

## Dataset sugli sport nel tempo

In [379]:
#Creo un dataset con le segeunti features:
# - sport: la categoria sportiva
# - year: anno dell'edizione olimpica
# - n_nations: numero di Paesi che hanno in quell'anno hanno partecipato ad eventi appartenenti a quella categoria sportiva
# - n_events: numero di eventi appartenenti a quella categoria sportiva
# - athletes_per_event: numero di atleti medio per evento nella categoria sportiva --> quanto è mediamente grande ogni evento sportivo nella categoria
# - pct_team_events: percentuali di eventi di squadra nella categoria sportiva (0 = tutti eventi individuali; 1 = tutti eventi a squadre)
# - hhi_gold: Herfindahl-Hirschman Index per medaglie d'oro --> Indice statistico che per la categoria sportiva misura la concentrazione delle medaglie d'oro tra i paesi, quindi la distribuzione delle medaglie d'oro tra i vari Paesi negli eventi sportivi appartenenti a quella categoria (se vicino a 1 un solo Paese vince tutti gli ori, se vicino a 0 gli ori sono distributi tra tanti paesi).
# - hhi_gold_athletes: Herfindahl-Hirschman Index per medaglie d'oro pesato per numero di atleti --> Paesi più efficienti in base al numero di atleti pesano di più
# - n_nations_with_gold: numero di nazioni che hanno vinto almeno una medaglia d'oro negli eventi di quella categoria sportiva
# - mean_gold_per_athletes: media degli ori per atleta tra i Paesi vincitori
# - hhi_total: Herfindahl-Hirschman Index per medaglie totali
# - hhi_total_athletes: Herfindahl-Hirschman Index per medaglie totali pesato per numero di atleti
# - n_nations_with_medal: numero di nazioni che hanno vinto almeno una medaglia negli eventi di quella categoria sportiva
# - mean_total_per_athletes: media delle medalie totali per atleta tra i Paesi vincitori di medaglia
# salvo il dataset per le analisi successive

sport_year = []

for (sport, year), grp in df_clean.groupby(['sport', 'year']):

    n_nations = grp['country_noc'].nunique()
    n_events = grp['event'].nunique()
    athletes_per_event = grp.groupby('event')['athlete_id'].nunique().mean()
    event_team_flag = grp.groupby('event')['isTeamSport'].first()
    pct_team_events = event_team_flag.mean()

    medals_grp = grp[grp['medal'].notna()]
    athletes_by_country = grp.groupby('country_noc')['num_athletes'].first()

    if len(medals_grp) > 0:

        gold_by_country = medals_grp[medals_grp['medal'] == 'Gold'].groupby('country_noc').size()
        total_gold = gold_by_country.sum()
        n_nations_with_gold = gold_by_country.shape[0]
        hhi_gold = ((gold_by_country / total_gold) ** 2).sum() if total_gold > 0 else np.nan
        gold_per_athl = (gold_by_country / athletes_by_country).dropna()
        hhi_gold_athl = ((gold_per_athl / gold_per_athl.sum()) **2).sum() if gold_per_athl.sum() > 0 else np.nan
        mean_gold_per_athl = gold_per_athl.mean()

        total_by_country = medals_grp.groupby('country_noc').size()
        total_medals = total_by_country.sum()
        n_nations_with_medal = total_by_country.shape[0]
        hhi_total = ((total_by_country / total_medals) ** 2).sum() if total_medals > 0 else np.nan
        total_per_athl = (total_by_country / athletes_by_country).dropna()
        hhi_total_athl = ((total_per_athl / total_per_athl.sum()) ** 2).sum() if total_per_athl.sum() > 0 else np.nan
        mean_total_per_athl = total_per_athl.mean()

    else:
        hhi_gold = np.nan
        hhi_gold_athl = np.nan
        n_nations_with_gold = 0
        mean_gold_per_athl = np.nan

        hhi_total = np.nan
        hhi_total_athl = np.nan
        n_nations_with_medal = 0
        mean_total_per_athl = np.nan

    sport_year.append({
        'sport': sport,
        'year': year,
        'n_nations': n_nations,
        'n_events': n_events,
        'athletes_per_event': athletes_per_event,
        'pct_team_events': pct_team_events,
        'hhi_gold': hhi_gold,
        'hhi_gold_athletes': hhi_gold_athl,
        'n_nations_with_gold': n_nations_with_gold,
        'mean_gold_per_athletes': mean_gold_per_athl,
        'hhi_total': hhi_total,
        'hhi_total_athletes': hhi_total_athl,
        'n_nations_with_medal': n_nations_with_medal,
        'mean_total_per_athletes': mean_total_per_athl,
    })

df_sport_year = pd.DataFrame(sport_year)
df_sport_year.to_csv("Sport_features_by_year.csv", index=False)
df_sport_year

,sport,year,n_nations,n_events,athletes_per_event,pct_team_events,hhi_gold,hhi_gold_athletes,n_nations_with_gold,mean_gold_per_athletes,hhi_total,hhi_total_athletes,n_nations_with_medal,mean_total_per_athletes
0,3x3 Basketball,2020,13,2,8.000000,1.0,0.500000,0.500000,2,0.250000,0.222222,0.209877,5,0.225000
1,Archery,1972,26,2,46.500000,0.0,1.000000,1.000000,1,0.333333,0.222222,0.214033,5,0.256667
2,Archery,1976,24,2,32.000000,0.0,1.000000,1.000000,1,0.500000,0.277778,0.295000,4,0.416667
3,Archery,1980,23,2,32.000000,0.0,0.500000,0.500000,2,0.250000,0.388889,0.368421,3,0.527778
4,Archery,1984,31,2,49.000000,0.0,0.500000,0.500000,2,0.166667,0.277778,0.271592,4,0.258333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,Wrestling,2008,54,18,18.666667,0.0,0.197531,0.164491,10,0.178526,0.056140,0.048945,29,0.310828
513,Wrestling,2012,63,18,18.555556,0.0,0.185596,0.176969,7,0.199117,0.067901,0.050588,28,0.319112
514,Wrestling,2016,62,18,19.000000,0.0,0.141975,0.134253,10,0.180716,0.065586,0.052154,27,0.326136
515,Wrestling,2020,57,18,15.777778,0.0,0.179012,0.157398,8,0.189883,0.062114,0.050427,26,0.340609
516,Wushu,2008,41,15,7.933333,0.0,NaN,NaN,0,NaN,NaN,NaN,0,NaN

In [380]:
df_clean[(df_clean['sport'] == 'Wushu') & (df_clean['edition'] != '2008 Summer Olympics')]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year, num_athletes]
Index: []

In [381]:
df_clean[(df_clean['sport'] == 'Wushu') & (df_clean['medal'] == 'Gold')]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year, num_athletes]
Index: []

In [382]:
df_clean[(df_clean['sport'] == 'Wushu') & (df_clean['medal'].notna())]

Empty DataFrame
Columns: [edition, edition_id, country_noc, sport, event, result_id, athlete, athlete_id, pos, medal, isTeamSport, year, num_athletes]
Index: []

## Dataset sul profilo di ogni sport (media sui vari anni)

In [383]:
#Creo un dataset sul profilo generico di ogni categoria sportiva (media storica su tutte le edizioni), le features sono:
# - sport: categoria sportiva
# - n_nations_mean: numero medio storico di Paesi partecipanti nei vari anni negli eventi sportivi appartenenti a quella categoria sportiva
# - n_nations_max: numero massimo storico di Paesi partecipanti
# - athletes_per_event: media storica di atleti per evento sportivo appartenente a quella categoria sportiva
# - pct_team_events: numero medio di eventi sportivi a squadre in quella categoria sportiva
# - hhi_gold_mean: concentrazione media storica delle medaglie d'oro (Herfindahl-Hirschman Index)
# - hhi_gold_athletes_mean: concentrazione media storica degli ori pesata per numero di atleti
# - mean_gold_per_athletes: media storica del rapporto ori/atleti tra i paesi vincitori di oro
# - n_nations_with_gold: numero medio storico di paesi che hanno vinto almeno una medaglia d'oro in quella categoria sportiva
# - hhi_total_mean: concentrazione media storica delle medaglie totali tra i paesi
# - hhi_total_athletes_mean: concentrazione media storica delle medaglie totali pesata per numero di atleti
# - n_nations_with_medal: media storica del numero di paesi che hanno vinto almeno una medaglia
# - mean_total_per_athletes: media storica del rapporto medaglie totali/atleti tra i paesi medagliati
# - n_editions: numero di edizioni olimpiche in cui era presente quella categoria sportiva
# salvo il dataset per le analisi successive

df_sport_profile = df_sport_year.groupby('sport').agg(
    n_nations_mean = ('n_nations', 'mean'),
    n_nations_max = ('n_nations', 'max'),
    athletes_per_event = ('athletes_per_event', 'mean'),
    pct_team_events = ('pct_team_events', 'mean'),
    hhi_gold_mean = ('hhi_gold', 'mean'),
    hhi_gold_athletes_mean = ('hhi_gold_athletes', 'mean'),
    mean_gold_per_athletes = ('mean_gold_per_athletes', 'mean'),
    n_nations_with_gold = ('n_nations_with_gold', 'mean'),
    hhi_total_mean = ('hhi_total', 'mean'),
    hhi_total_athletes_mean = ('hhi_total_athletes', 'mean'),
    n_nations_with_medal = ('n_nations_with_medal', 'mean'),
    mean_total_per_athletes = ('mean_total_per_athletes', 'mean'),
    n_editions = ('year', 'nunique'),
).reset_index()

df_sport_profile.to_csv("Sport_profile_static.csv", index=False)
df_sport_profile

,sport,n_nations_mean,n_nations_max,athletes_per_event,pct_team_events,hhi_gold_mean,hhi_gold_athletes_mean,mean_gold_per_athletes,n_nations_with_gold,hhi_total_mean,hhi_total_athletes_mean,n_nations_with_medal,mean_total_per_athletes,n_editions
0,3x3 Basketball,13.000000,13,8.000000,1.000000,0.500000,0.500000,0.250000,2.000000,0.222222,0.209877,5.000000,0.225000,1
1,Archery,37.846154,50,38.619231,0.353846,0.648462,0.627990,0.360897,1.923077,0.242051,0.226660,6.076923,0.350373,13
2,Artistic Gymnastics,35.600000,59,74.066667,0.142857,0.275273,0.258385,0.279776,6.266667,0.215933,0.192367,10.200000,0.492368,15
3,Artistic Swimming,20.600000,24,19.250000,0.850000,0.955556,0.955556,0.332222,1.100000,0.324889,0.324637,3.200000,0.333056,10
4,Athletics,105.533333,134,37.096529,0.091415,0.140041,0.115076,0.084064,17.533333,0.101936,0.059095,32.600000,0.132437,15
5,Badminton,34.400000,50,23.390000,0.580000,0.487500,0.491405,0.152416,2.300000,0.267092,0.224149,4.900000,0.216853,10
6,Baseball,6.888889,8,6.888889,1.000000,1.000000,1.000000,0.044444,0.666667,0.333333,0.333333,2.000000,0.044444,9
7,Basketball,15.600000,18,11.633333,1.000000,0.833333,0.837037,0.070833,1.333333,0.270370,0.266240,4.133333,0.072917,15
8,Basque pelota,7.500000,8,4.425000,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,2
9,Beach Volleyball,22.857143,24,19.214286,1.000000,0.571429,0.602340,0.167857,1.857143,0.269841,0.276948,4.285714,0.229762,7
10,Bowling,20.000000,20,12.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,1
11,Boxing,66.533333,89,25.470497,0.000000,0.239113,0.212503,0.199270,6.933333,0.083427,0.067797,20.866667,0.342639,15
12,Canoe Slalom,25.555556,32,21.138889,0.222222,0.416667,0.442730,0.240346,3.111111,0.183642,0.175514,7.111111,0.301831,9
13,Canoe Sprint,36.333333,47,17.459596,0.559235,0.269726,0.273994,0.220907,5.733333,0.129913,0.129861,12.933333,0.322343,15
14,Cycling BMX Freestyle,11.000000,11,9.000000,0.000000,0.500000,0.500000,0.500000,2.000000,0.222222,0.235556,5.000000,0.750000,1
15,Cycling BMX Racing,21.750000,23,24.000000,0.000000,0.500000,0.544165,0.295833,2.000000,0.305556,0.323304,3.750000,0.494028,4
16,Cycling Mountain Bike,33.857143,37,38.357143,0.000000,0.500000,0.583003,0.366667,2.000000,0.230159,0.235327,5.285714,0.356746,7
17,Cycling Road,48.333333,67,70.950000,0.233333,0.421296,0.441819,0.178142,2.866667,0.203692,0.202122,6.466667,0.220747,15
18,Cycling Track,35.266667,47,20.558095,0.295635,0.359919,0.353335,0.237940,4.466667,0.160528,0.143680,10.733333,0.314977,15
19,Diving,28.200000,42,24.450000,0.200000,0.550000,0.552917,0.288041,2.533333,0.312500,0.284526,5.733333,0.422889,15
20,Equestrian Dressage,16.866667,28,25.766667,0.500000,0.700000,0.708333,0.410000,1.600000,0.366667,0.364083,3.266667,0.551019,15
21,Equestrian Eventing,18.800000,29,32.966667,0.500000,0.766667,0.766942,0.310000,1.466667,0.329037,0.333623,3.600000,0.391111,15
22,Equestrian Jumping,23.200000,35,35.200000,0.500000,0.766667,0.766667,0.255556,1.466667,0.294704,0.296916,3.933333,0.336667,15
23,Fencing,37.800000,46,29.554444,0.473333,0.252759,0.255189,0.130545,5.200000,0.171306,0.159209,9.066667,0.219712,15
24,Football,17.600000,23,13.733333,1.000000,0.766667,0.773591,0.046214,1.466667,0.257407,0.260468,4.333333,0.048127,15
25,Golf,41.000000,42,59.750000,0.000000,0.750000,0.760000,0.229167,1.500000,0.194444,0.225858,5.500000,0.349405,2
26,Handball,15.846154,19,10.692308,1.000000,0.653846,0.662855,0.056287,1.692308,0.217949,0.216229,5.076923,0.058319,13
27,Hockey,13.800000,16,11.533333,1.000000,0.633333,0.644444,0.040278,1.733333,0.255556,0.257280,4.400000,0.046650,15
28,Judo,67.928571,105,24.620323,0.004762,0.264701,0.266900,0.286243,6.571429,0.094355,0.082956,18.500000,0.365050,14
29,Karate,35.000000,35,9.875000,0.000000,0.125000,0.188419,0.461458,8.000000,0.062500,0.058882,20.000000,0.694821,1
30,Kendo,2.000000,2,12.250000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,1
31,Marathon Swimming,30.000000,32,25.125000,0.000000,0.625000,0.688889,0.697917,1.750000,0.222222,0.232611,5.250000,0.546528,4
32,Modern Pentathlon,23.000000,31,33.033333,0.266667,0.700000,0.702667,0.444444,1.600000,0.275852,0.286314,4.333333,0.473889,15
33,Rhythmic Gymnastics,21.400000,24,24.500000,0.350000,0.900000,0.918000,0.324107,1.200000,0.366667,0.381993,3.400000,0.367440,10
34,Roller Hockey,11.000000,11,11.000000,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,1
35,Rowing,44.000000,74,13.795238,0.857143,0.231973,0.253171,0.098939,7.600000,0.110582,0.110865,15.666667,0.135742,15
36,Rugby Sevens,15.000000,16,12.000000,1.000000,0.500000,0.500096,0.038846,2.000000,0.222222,0.218900,5.000000,0.065160,2
37,Sailing,51.733333,68,24.588990,0.641869,0.199545,0.203243,0.114783,6.266667,0.104780,0.105857,14.133333,0.176269,15
38,Shooting,71.600000,95,41.802456,0.013333,0.177840,0.181293,0.157353,7.800000,0.109052,0.097822,16.866667,0.256307,15
39,Skateboarding,25.000000,25,20.000000,0.000000,0.625000,0.520000,0.250000,2.000000,0.277778,0.241152,5.000000,0.323333,1
40,Softball,7.600000,8,7.600000,1.000000,1.000000,1.000000,0.066667,1.000000,0.333333,0.333333,3.000000,0.066667,5
41,Sport Climbing,19.000000,19,20.000000,0.000000,0.500000,0.555556,0.750000,2.000000,0.222222,0.239669,5.000000,0.550000,1
42,Surfing,18.000000,18,20.000000,0.000000,0.500000,0.500000,0.250000,2.000000,0.222222,0.283951,5.000000,0.450000,1
43,Swimming,84.066667,129,35.326021,0.183353,0.322874,0.258876,0.167483,8.066667,0.203368,0.133116,15.733333,0.260813,15
44,Table Tennis,49.333333,54,39.400000,0.511111,0.817840,0.808876,0.422288,1.444444,0.355734,0.323924,4.666667,0.394755,9
45,Taekwondo,47.875000,58,13.078125,0.000000,0.208333,0.211692,0.456845,4.500000,0.069119,0.065770,14.375000,0.569486,8
46,Tennis,41.909091,53,35.054545,0.490909,0.377284,0.412357,0.278475,2.727273,0.149918,0.175362,7.090909,0.324542,11
47,Trampolining,17.166667,20,15.333333,0.000000,0.666667,0.680960,0.513889,1.666667,0.342593,0.308853,3.833333,0.611574,6
48,Triathlon,36.333333,42,50.527778,0.055556,0.472222,0.513119,0.256944,2.166667,0.238683,0.258009,5.000000,0.315833,6
49,Volleyball,15.066667,19,10.500000,1.000000,0.566667,0.585185,0.054167,1.866667,0.233333,0.230740,4.800000,0.064954,15
50,Water Polo,13.333333,16,11.733333,1.000000,0.800000,0.818519,0.072106,1.400000,0.281481,0.282523,3.933333,0.073981,15
51,Waterskiing,16.000000,16,10.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,1
52,Weightlifting,56.600000,77,18.212698,0.000000,0.284267,0.248392,0.299721,6.133333,0.125572,0.110782,14.800000,0.401765,15
53,Wrestling,52.400000,68,18.289352,0.000000,0.211307,0.175471,0.177384,8.600000,0.097344,0.073971,20.466667,0.285118,15
54,Wushu,41.000000,41,7.933333,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,1

## Dataset sul successo olimpico

In [384]:
# Creo un dataset che misura il successo olimpico storico di ogni paese in ogni categoria sportiva:
# - country_noc: codice noc del paese
# - sport: categoria sportiva
# - success_score_mean: media storica del rapporto ori/atleti per edizione olimpica
# - total_golds: numero totale di ori vinti storicamente in quella categoria sportiva
# - total_athletes: numero totale di atleti inviati storicamente in quella categoria sportiva
# - gold_per_athletes: ori totali / atleti totali storici (efficienza aggregata del paese in quello sport)
# salvo il dataset per le analisi successive

athletes_by_csy = df_clean.groupby(['country_noc', 'sport', 'year'])['athlete_id'].nunique().reset_index()
athletes_by_csy.columns = ['country_noc', 'sport', 'year', 'athletes_sent']

gold_by_csy = (
    df_clean[df_clean['medal'] == 'Gold']
    .groupby(['country_noc', 'sport', 'year'])
    .size()
    .reset_index(name='golds_won')
)

success_df = athletes_by_csy.merge(gold_by_csy, on=['country_noc', 'sport', 'year'], how='left')
success_df['golds_won'] = success_df['golds_won'].fillna(0)
success_df['success_score'] = success_df['golds_won'] / success_df['athletes_sent']

df_success_country_sport = success_df.groupby(['country_noc', 'sport']).agg(
    success_score_mean = ('success_score', 'mean'),
    total_golds = ('golds_won', 'sum'),
    total_athletes = ('athletes_sent', 'sum'),
).reset_index()

#ori totali / atleti totali storici: efficienza aggregata del paese in quello sport
df_success_country_sport['gold_per_athletes'] = (df_success_country_sport['total_golds'] / df_success_country_sport['total_athletes'])

df_success_country_sport.to_csv("Success_score_country_sport.csv", index=False)
df_success_country_sport

,country_noc,sport,success_score_mean,total_golds,total_athletes,gold_per_athletes
0,AFG,Athletics,0.000000,0.0,12,0.00
1,AFG,Boxing,0.000000,0.0,5,0.00
2,AFG,Judo,0.000000,0.0,3,0.00
3,AFG,Shooting,0.000000,0.0,1,0.00
4,AFG,Swimming,0.000000,0.0,1,0.00
...,...,...,...,...,...,...
3286,ZIM,Shooting,0.000000,0.0,17,0.00
3287,ZIM,Swimming,0.090909,2.0,25,0.08
3288,ZIM,Tennis,0.000000,0.0,13,0.00
3289,ZIM,Triathlon,0.000000,0.0,3,0.00
3290,ZIM,Weightlifting,0.000000,0.0,1,0.00

## Dataset sui singoli eventi

In [385]:
#Creo un dataset con le seguenti features per ogni combinazione evento + anno:
# - sport: categoria sportiva a cui appartiene l'evento
# - event: nome dell'evento sportivo appartenente a quella categoria
# - year: anno dell'edizione olimpica
# - n_nations: numero di paesi partecipanti all'evento in quell'anno
# - n_athletes: numero totale di atleti partecipanti all'evento in quell'anno
# - is_team_event: indica se l'evento è a squadre o individuale
# - gold_per_athlete: media tra i paesi del rapporto ori/atleti --> efficienza normalizzata per dimensione del paese
# - n_nations_with_gold: numero di paesi che hanno vinto l'oro (in un singolo evento per anno è sempre 1)
# - total_per_athlete: media tra i paesi del rapporto medaglie totali/atleti
# - n_nations_with_medal: numero di paesi che hanno vinto almeno una medaglia
# salvo il dataset per le analisi successive

# In questo dataset non creo la feature sull'hhi perché in un singolo evento per anno c'è sempre un solo oro (l'hhi sarebbe sempre 1 e non aggiungerebbe informazione)

event_year_rows = []

for (sport, event, year), grp in df_clean.groupby(['sport', 'event', 'year']):

    n_nations  = grp['country_noc'].nunique()
    n_athletes = grp['athlete_id'].nunique()
    is_team    = grp['isTeamSport'].iloc[0]

    medals_grp = grp[grp['medal'].notna()]
    athletes_by_country = grp.groupby('country_noc')['num_athletes'].first()

    if len(medals_grp) > 0:

        gold_by_country = medals_grp[medals_grp['medal'] == 'Gold'].groupby('country_noc').size()
        n_nations_with_gold = gold_by_country.shape[0]
        gold_per_athlete = (gold_by_country / athletes_by_country).dropna().mean()

        total_by_country = medals_grp.groupby('country_noc').size()
        n_nations_with_medal = total_by_country.shape[0]
        total_per_athlete = (total_by_country / athletes_by_country).dropna().mean()

    else:
        n_nations_with_gold  = 0
        gold_per_athlete     = np.nan
        n_nations_with_medal = 0
        total_per_athlete    = np.nan

    event_year_rows.append({
        'sport':               sport,
        'event':               event,
        'year':                year,
        'n_nations':           n_nations,
        'n_athletes':          n_athletes,
        'is_team_event':       is_team,
        'gold_per_athlete':     gold_per_athlete,
        'n_nations_with_gold':  n_nations_with_gold,
        'total_per_athlete':    total_per_athlete,
        'n_nations_with_medal': n_nations_with_medal
    })

df_event_year = pd.DataFrame(event_year_rows)
df_event_year.to_csv("Event_features_by_year.csv", index=False)
df_event_year

,sport,event,year,n_nations,n_athletes,is_team_event,gold_per_athlete,n_nations_with_gold,total_per_athlete,n_nations_with_medal
0,3x3 Basketball,"3x3 Basketball, Men",2020,8,8,True,0.250000,1,0.208333,3
1,3x3 Basketball,"3x3 Basketball, Women",2020,8,8,True,0.250000,1,0.166667,3
2,Archery,"Individual, Men",1972,23,54,False,0.166667,1,0.233333,3
3,Archery,"Individual, Men",1976,23,37,False,0.250000,1,0.250000,3
4,Archery,"Individual, Men",1980,23,36,False,0.250000,1,0.277778,3
...,...,...,...,...,...,...,...,...,...,...
3872,Wushu,"Sanshou (≤60 kilograms), Women",2008,7,7,False,NaN,0,NaN,0
3873,Wushu,"Sanshou (≤70 kilograms), Men",2008,7,7,False,NaN,0,NaN,0
3874,Wushu,"Sanshou (≤85 kilograms), Men",2008,8,8,False,NaN,0,NaN,0
3875,Wushu,"Taijiquan & Taijijuan, Men",2008,8,8,False,NaN,0,NaN,0
3876,Wushu,"Taijiquan & Taijijuan, Women",2008,7,7,False,NaN,0,NaN,0

## Dataset sul profilo di ogni evento sportivo (media sui vari anni)

In [386]:
# Funzione per calcolare l'hhi su un gruppo di paesi, per calcolare se in quell'evento ha sempre vinto l'oro un unico paese o se nel corso del tempo hanno vinto paesi diversi
def hhi_from_group(g):
    total = g['golds_won'].sum()
    return ((g['golds_won'] / total) ** 2).sum() if total > 0 else np.nan

In [387]:
#Creo un dataset sul profilo generico di ogni evento sportivo (media storica su tutte le edizioni):
# - sport: categoria sportiva a cui appartiene l'evento
# - event: nome dell'evento sportivo appartenente a quella categoria
# - is_team_event: indica se l'evento è a squadre o individuale
# - n_nations_mean: media storica del numero di paesi partecipanti
# - n_nations_max: massimo storico del numero di paesi partecipanti
# - n_athletes_mean: media storica del numero di atleti partecipanti
# - gold_per_athlete: media storica del rapporto ori/atleti tra i paesi vincitori
# - n_nations_with_gold: media storica del numero di paesi che hanno vinto l'oro
# - total_per_athlete: media storica del rapporto medaglie totali/atleti tra i paesi medagliati
# - n_nations_with_medal: media storica del numero di paesi che hanno vinto almeno una medaglia
# - n_editions: numero di edizioni olimpiche in cui è stato presente quell'evento
# - hhi_gold: concentrazione storica degli ori (misura se lo stesso paese vince sempre o se l'oro cambia mani nel tempo)
# - hhi_total: concentrazione storica delle medaglie totali tra i paesi

df_event_profile = df_event_year.groupby(['sport', 'event', 'is_team_event']).agg(
    n_nations_mean      = ('n_nations', 'mean'),
    n_nations_max       = ('n_nations', 'max'),
    n_athletes_mean     = ('n_athletes', 'mean'),
    gold_per_athlete        = ('gold_per_athlete', 'mean'),
    n_nations_with_gold     = ('n_nations_with_gold', 'mean'),
    total_per_athlete       = ('total_per_athlete', 'mean'),
    n_nations_with_medal    = ('n_nations_with_medal', 'mean'),
    n_editions          = ('year', 'nunique'),
).reset_index()

gold_winner_by_event = (
    df_clean[df_clean['medal'] == 'Gold']
    .groupby(['sport', 'event', 'country_noc'])
    .size()
    .reset_index(name='golds_won')
)

hhi_event = (
    gold_winner_by_event
    .groupby(['sport', 'event'])
    .apply(hhi_from_group)
    .reset_index(name='hhi_gold')
)

total_winner_by_event = (
    df_clean[df_clean['medal'].notna()]
    .groupby(['sport', 'event', 'country_noc'])
    .size()
    .reset_index(name='medals_won')
)

hhi_event_total = (
    total_winner_by_event
    .groupby(['sport', 'event'])
    .apply(lambda g: ((g['medals_won'] / g['medals_won'].sum()) ** 2).sum())
    .reset_index(name='hhi_total')
)

df_event_profile = df_event_profile.merge(hhi_event, on=['sport', 'event'], how='left')
df_event_profile = df_event_profile.merge(hhi_event_total, on=['sport', 'event'], how='left')

df_event_profile.to_csv("Event_profile_static.csv", index=False)

df_event_profile

,sport,event,is_team_event,n_nations_mean,n_nations_max,n_athletes_mean,gold_per_athlete,n_nations_with_gold,total_per_athlete,n_nations_with_medal,n_editions,hhi_gold,hhi_total
0,3x3 Basketball,"3x3 Basketball, Men",True,8.000000,8,8.000000,0.250000,1.0,0.208333,3.000000,1,1.000000,0.333333
1,3x3 Basketball,"3x3 Basketball, Women",True,8.000000,8,8.000000,0.250000,1.0,0.166667,3.000000,1,1.000000,0.333333
2,Archery,"Individual, Men",False,30.384615,37,58.538462,0.214103,1.0,0.219658,2.923077,13,0.207101,0.109796
3,Archery,"Individual, Women",False,27.769231,38,52.769231,0.179487,1.0,0.317308,2.076923,13,0.514793,0.270217
4,Archery,"Team, Men",True,14.444444,21,14.444444,0.175926,1.0,0.182099,3.000000,9,0.481481,0.163237
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Wushu,"Sanshou (≤60 kilograms), Women",False,7.000000,7,7.000000,NaN,0.0,NaN,0.000000,1,NaN,NaN
453,Wushu,"Sanshou (≤70 kilograms), Men",False,7.000000,7,7.000000,NaN,0.0,NaN,0.000000,1,NaN,NaN
454,Wushu,"Sanshou (≤85 kilograms), Men",False,8.000000,8,8.000000,NaN,0.0,NaN,0.000000,1,NaN,NaN
455,Wushu,"Taijiquan & Taijijuan, Men",False,8.000000,8,8.000000,NaN,0.0,NaN,0.000000,1,NaN,NaN
456,Wushu,"Taijiquan & Taijijuan, Women",False,7.000000,7,7.000000,NaN,0.0,NaN,0.000000,1,NaN,NaN